### DISCUSSION TITLE
Nginx Proxy getting 502 on static files after update.

### DISCUSSION THREAD

**Discussion by AndresJ551** [mastodon/mastodon#20506] [Q&A] [answered]
Hello!
I will start with the manual I used to install and run successfully Mastodon with Docker and Nginx as Proxy.
https://sleeplessbeastie.eu/2022/05/02/how-to-take-advantage-of-docker-to-install-mastodon/
This worked as a charm with v3.5.1 but once I changed the docker-compose to use v3.5.3 the static files (css, js) are broken.
My instance is running and responding to the fediverse, but clearly my frontend is not. (https://mastodon.hardcoredevs.com/)
I have recreated the static files running:
sudo docker run --rm -v "temporary_static:/static" tootsuite/mastodon:v3.5.1 bash -c "cp -r /opt/mastodon/public/* /static/"
And then running rails assets:precompile without luck.
My question comes to, where in the Nginx config file is routing the static files? I'm getting to the conclusion that
```
location / {
   try_files $uri @proxy;
}
```
But @proxy is "backend" and backend is sidekiq???
```
upstream backend {
    server 127.0.0.1:3000 fail_timeout=0;
}
```
It seems like "website" is missing and I have added to my Nginx config to get it to work.
```
upstream  mastodon.hardcoredevs.com {
	server mastodon:3000;
}
```
It seems like "website" is missing and I have added to my Nginx config to get it to work:

Here is my current working Nginx config file:
```
map $http_upgrade $connection_upgrade {
	default upgrade;
	''	close;
}

upstream  mastodon.hardcoredevs.com {
	server mastodon:3000;
}

upstream streaming {
	server mastodon_stream:4000 fail_timeout=0;
}

upstream backend {
	server sidekiq:3000 fail_timeout=0;
}

proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=CACHE:10m inactive=7d max_size=1g;

server {
	server_name mastodon.hardcoredevs.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	# Do not HTTPS redirect Let'sEncrypt ACME challenge
	location ^~ /.well-known/acme-challenge/ {
		auth_basic off;
		auth_request off;
		allow all;
		root /usr/share/nginx/html;
		try_files $uri =404;
		break;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}

server {
	server_name mastodon.hardcoredevs.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/mastodon.hardcoredevs.com.crt;
	ssl_certificate_key /etc/nginx/certs/mastodon.hardcoredevs.com.key;
	ssl_dhparam /etc/nginx/certs/mastodon.hardcoredevs.com.dhparam.pem;
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_trusted_certificate /etc/nginx/certs/mastodon.hardcoredevs.com.chain.pem;
	add_header Strict-Transport-Security "max-age=31536000" always;
	include /etc/nginx/vhost.d/default;
	keepalive_timeout 70;
	sendfile on;
	client_max_body_size 80m;
	root /opt/mastodon/web/public/;
	
	gzip on;
	gzip_disable "msie6";
	gzip_vary on;
	gzip_proxied any;
	gzip_comp_level 6;
	gzip_buffers 16 8k;
	gzip_http_version 1.1;
	gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml image/x-icon;

	add_header Strict-Transport-Security "max-age=31536000" always;

	location / {  
		#try_files $uri @proxy;
		proxy_pass http://mastodon.hardcoredevs.com;
	}

	location /sw.js {
		add_header Cache-Control "public, max-age=0";
		add_header Strict-Transport-Security "max-age=31536000" always;
		try_files $uri @proxy;
	}

	location ~ ^/(system/accounts/avatars|system/media_attachments/files) {
		add_header Cache-Control "public, max-age=31536000, immutable";
		add_header Strict-Transport-Security "max-age=31536000" always;
		root /opt/mastodon/;
		try_files $uri @proxy;
	}

	location ~ ^/(emoji|packs) {
		add_header Cache-Control "public, max-age=31536000, immutable";
		add_header Strict-Transport-Security "max-age=31536000" always;
		try_files $uri @proxy;
	}

	location @proxy {
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header Proxy "";
		proxy_pass_header Server;

		proxy_pass http://backend;
		proxy_buffering on;
		proxy_redirect off;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;

		proxy_cache CACHE;
		proxy_cache_valid 200 7d;
		proxy_cache_valid 410 24h;
		proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
		add_header X-Cached $upstream_cache_status;
		add_header Strict-Transport-Security "max-age=31536000" always;

		tcp_nodelay on;
	}

	location /api/v1/streaming {
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header Proxy "";

		proxy_pass http://streaming;
		proxy_buffering off;
		proxy_redirect off;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;

		tcp_nodelay on;
	}
}
```
And this is the Docker-Compose.yml:
```
version: '3'                                                                                                                                                                                                                                                                                                        
                                                              
services:                                                                                                                                                     
  postgresql:                             
    image: postgres:14                 
    env_file: database.env                                                     
    restart: always
    shm_size: 256mb                 
    healthcheck:                                  
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:    
      - internal_network

  redis:
    image: redis:7
    restart: always                    
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - redis:/data
    networks:
      - internal_network

  redis-volatile:  
    image: redis:7
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    networks:
      - internal_network

  elasticsearch:
    image: elasticsearch:7.17.3
    restart: always
    env_file: database.env
    environment:
      - cluster.name=elasticsearch-mastodon
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ingest.geoip.downloader.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "nc -z elasticsearch 9200"]
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - internal_network

  website:
    image: tootsuite/mastodon:latest
    env_file:
      - application.env
      - database.env
    command: bash -c "bundle exec rails s -p 3000"
    restart: always
    environment:
      - LETSENCRYPT_HOST=mastodon.hardcoredevs.com
    depends_on:
      - postgresql
      - redis
      - redis-volatile
      - elasticsearch
    networks:
      - internal_network
      - Main
    hostname: mastodon
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    volumes:
      - uploads:/mastodon/public/system

  shell:
    image: tootsuite/mastodon:latest
    env_file:
      - application.env
      - database.env
    command: /bin/bash
    restart: "no"
    networks:
      - internal_network
      - Main
    volumes:
      - uploads:/mastodon/public/system

  streaming:
    image: tootsuite/mastodon:latest
    env_file:
      - application.env
      - database.env
    command: node ./streaming
    restart: always
    depends_on:
      - postgresql
      - redis
      - redis-volatile
      - elasticsearch
    networks:
      - internal_network
      - Main
    hostname: mastodon_stream
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']

  sidekiq:
    image: tootsuite/mastodon:latest
    env_file:
      - application.env
      - database.env
    command: bundle exec sidekiq
    restart: always
    depends_on:
      - postgresql
      - redis
      - redis-volatile
      - website
    networks:
      - internal_network
      - Main
    hostname: sidekiq
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
    volumes:
      - uploads:/mastodon/public/system

networks:
  #Main is shared with Nginx_Proxy's container, not included in this compose.
  Main:
	external: true
  internal_network:
	internal: true

volumes:
  postgresql:
    driver_opts:
      type: none
      device: /opt/mastodon/database/postgresql
      o: bind
  redis:
    driver_opts:
      type: none
	  device: /opt/mastodon/database/redis
	  o: bind
  elasticsearch:
    driver_opts:
	  type: none
	  device: /opt/mastodon/database/elasticsearch
	  o: bind
  uploads:
    driver_opts:
	  type: none
	  device: /opt/mastodon/web/system
	  o: bind
```
Any help is appreciated!
