### DISCUSSION TITLE
Mastondon & Cloudflare Tunnels

### DISCUSSION THREAD

**Discussion by zsamboky** [mastodon/mastodon#20913] [General]
Can anyone point me to instructions on how to tunnel all traffic through a CF tunnel to a Mastodon server?

**Comment by ineffyble** [comment]
I'm not aware of any, although it _should_ be possible.

**Comment by madeofstown** [comment]
Should be as simple as flipping the "proxy" switch in your DNS A record. I don't think a tutorial is really needed.

**Reply by ineffyble** [reply]
I believe this is referring to https://www.cloudflare.com/en-au/products/tunnel/ not Cloudflare CDN

**Reply by zsamboky** [reply]
Correct! Thanks for the clarification.

**Comment by bearice** [comment]
you should checkout Zero-trust console: https://one.dash.cloudflare.com/ , there is a step-by-step guide UI in `Access` -> `Tunnel` .

**Reply by bearice** [reply]
And one more hint it to set "HTTP Host Header" in "Additional application settings" or you will get an 403 error.

**Reply by zsamboky** [reply]
Thanks for this hint! I am indeed getting the 403. What to I set  for "HTTP Host Header"? I tried "CF-Connecting-IP" but no go.

**Reply by bearice** [reply]
set to your `LOCAL_DOMAIN` , this is the Host header sent to your instance by Cloudflare. (it awkwardly didn't forward the request in full)

**Reply by zsamboky** [reply]
Thank you very much. It is now working!

**Reply by Ale4224** [reply]
to what port did you point the tunnel to? if I point it to http 80 i get infinite loops, but if I point to the 443 in https I get a TLS error

**Comment by zsiegel** [comment]
One thing to note is here is that you do need to set a configuration for streaming to work! Here is an example of a config that ensures everything works with tunnels.

```yaml
ingress:
  - hostname: my_domain.social
    path: \/api\/v1\/streaming\/
    service: http://streaming:4000
  - hostname: my_domain.social
    service: http://mastodon:3000
  - service: http_status:404
```

In my docker setup the streaming container name is `streaming` and the main rails app is named `mastodon`
