### DISCUSSION TITLE
Sidekiq and kubernetes

### DISCUSSION THREAD

**Discussion by oculos** [mastodon/mastodon#21822] [Q&A]
Hi,

I want to create a more resilient Mastodon server, and would like to split the sidekiq processes.
If I have three worker nodes on my cluster, I thought about having a few pods with the default queue, a few less with the push, and so on.
Is this scenario doable, or each separate pod needs to have all the queues enabled? 
And how can one monitor sidekiq in such scenario? 

Best,
Francis

**Comment by larsgrah** [comment]
Assuming you use the helm chart:

you can add more workers here: 

```
mastodon:
  sidekiq:
    # -- Pod security context for all Sidekiq Pods, overwrites .Values.podSecurityContext
    podSecurityContext: {}
    # -- (Sidekiq Container) Security Context for all Pods, overwrites .Values.securityContext
    securityContext: {}
    # -- Resources for all Sidekiq Deployments unless overwritten
    resources: {}
    # -- Affinity for all Sidekiq Deployments unless overwritten, overwrites .Values.affinity
    affinity: {}
    # limits:
    #   cpu: "1"
    #   memory: 768Mi
    # requests:
    #   cpu: 250m
    #   memory: 512Mi
    workers:
      - name: all-queues
        # -- Number of threads / parallel sidekiq jobs that are executed per Pod
        concurrency: 25
        # -- Number of Pod replicas deployed by the Deployment
        replicas: 1
        # -- Resources for this specific deployment to allow optimised scaling, overwrites .Values.mastodon.sidekiq.resources
        resources: {}
        # -- Affinity for this specific deployment, overwrites .Values.affinity and .Values.mastodon.sidekiq.affinity
        affinity: {}
        # -- Sidekiq queues for Mastodon that are handled by this worker. See https://docs.joinmastodon.org/admin/scaling/#concurrency
        # See https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues for how to weight queues as argument
        queues:
          - ingress
          - default
          - push
          - mailers
          - pull
          - scheduler # Make sure the scheduler queue only exists once and with a worker that has 1 replica.
```
with different names, replicas and queues
