### DISCUSSION TITLE
True dark mode

### DISCUSSION THREAD

**Discussion by aeharding** [mastodon/mastodon#22800] [Show and tell]
One thing I really miss about Twitter is the true dark mode. It just is so much more readable in my opinion.

It would be great if a true dark mode was implemented, but until then, you can apply the following CSS via `/admin/settings/appearance` (if admin) or an extension (like [stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/), if you're a user)

I'm sure this could be hacked further to make it look better, this is only like 10 mins of work, so feel free to post below with your improvements! 😁

**Important note:** If you are a server admin and want to roll out these tweaks, I highly recommend prefixing every single selector with `.theme-default `. This will ensure that these tweaks do not break light/high contrast themes. Dark theme being the default theme is required for this, however.

```css
body,
.tabs-bar__wrapper,
.column > .scrollable,
.detailed-status,
.detailed-status__action-bar,
.column-header__back-button,
.admin-wrapper .sidebar-wrapper__inner,
.search__input,
.account__header,
.account__section-headline, .notification__filter-bar {
  background: #000 !important;
}

.column-header > button,
.column-back-button,
.column-header > button,
.column-header__button,
.column-header {
  background: none !important;
}

.tabs-bar__wrapper {
  background: rgba(0, 0, 0, 0.5) !important;
  backdrop-filter: blur(10px) saturate(200%);
}

.compose-form .autosuggest-textarea__textarea,
.compose-form .spoiler-input__input {
  color: inherit !important;
  background: none !important;
}

.compose-panel .compose-form__autosuggest-wrapper {
 background-color: rgba(255, 255, 255, 0.06) !important;
}

.compose-form .compose-form__buttons-wrapper,
.compose-form .compose-form__modifiers {
  background: none !important;
}

.compose-form .emoji-picker-dropdown {
  display: none;
}
```

<img width="1666" alt="image" src="https://user-images.githubusercontent.com/2166114/209743382-6a5e2a40-26dc-49fd-a071-6310f0908767.png">
