### DISCUSSION TITLE
Unable to write to Volume in Docker

### DISCUSSION THREAD

**Discussion by RainerZufall187** [mastodon/mastodon#23875] [Q&A] [answered]
hiiii

My Mastodon is unable to write to /mastodon/public/system or /opt/mastodon/public/system with its default user `mastodon`. If I execute a console in the web container as root, I can write without any problems.

Is it somehow possible to pass GID and UID wíth env vars in my .env.production or something?

docker-compose.yml:
```yml
services:
  db:
    restart: always
    image: postgres:15-alpine
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./postgres15:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_USER=mastodon'
      - 'POSTGRES_PASSWORD=ok'

  redis:
    restart: always
    image: redis:latest
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis:/data

  web:
    image: tootsuite/mastodon:edge
    restart: always
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    depends_on:
      - db
      - redis
    volumes:
      - ./public/system:/mastodon/public/system

  streaming:
    image: tootsuite/mastodon:edge
    restart: always
    env_file: .env.production
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']
    depends_on:
      - db
      - redis

  sidekiq:
    image: tootsuite/mastodon:edge
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    volumes:
      - ./cloudflared:/etc/cloudflared
    command: tunnel run mastodon
    networks:
      - external_network
      - internal_network

networks:
  external_network:
  internal_network:
    internal: true
```
