### DISCUSSION TITLE
I give up, how do you use tootctl to list your local users?

### DISCUSSION THREAD

**Discussion by TheGorf** [mastodon/mastodon#25147] [Q&A]
Pretty much just as it says. The documentation has no reference to a "list" options in the accounts.  nothing like "tootctl accounts list" or anything. Consequently I can't figure out how the hell to find the username of users so I can fix the accounts. Am I really expected to muck about in the data base and try to figure it out? 

```
docker exec -it web tootctl accounts
Commands:
  tootctl accounts approve [USERNAME]             # Approve pending accounts
  tootctl accounts backup USERNAME                # Request a backup for a user
  tootctl accounts create USERNAME --email=EMAIL  # Create a new user account
  tootctl accounts cull [DOMAIN...]               # Remove remote accounts that no longer exist
  tootctl accounts delete [USERNAME]              # Delete a user
  tootctl accounts fix-duplicates                 # Find duplicate remote accounts and merge them
  tootctl accounts follow USERNAME                # Make all local accounts follow account specified by USERNAME
  tootctl accounts help [COMMAND]                 # Describe subcommands or one specific subcommand
  tootctl accounts merge FROM TO                  # Merge two remote accounts into one
  tootctl accounts migrate USERNAME               # Migrate a local user to another account
  tootctl accounts modify USERNAME                # Modify a user account
  tootctl accounts prune                          # Prune remote accounts that never interacted with local users
  tootctl accounts refresh [USERNAMES]            # Fetch remote user data and files
  tootctl accounts reset-relationships USERNAME   # Reset all follows and/or followers for a user
  tootctl accounts rotate [USERNAME]              # Generate and broadcast new keys
  tootctl accounts unfollow ACCT                  # Make all local accounts unfollow account specified by ACCT
```
And no of my attempts to just guess seem to work either:

```
$ docker exec -it web tootctl accounts modify @Gorf@m***s --role Admin
No user with such username
$ docker exec -it web tootctl accounts modify @Gorf --role Admin
No user with such username
$ docker exec -it web tootctl accounts modify Gorf@m***s --role Admin
No user with such username
```

**Comment by palonza** [comment]
Hi @TheGorf ,

Access the Mastodon web container using the following command:

```bash
docker exec -it web bash
```

Once you're inside the web container, connect to the PostgreSQL database by running:
```bash
RAILS_ENV=production bundle exec rails dbconsole
```
then run follow query:
```SQL
SELECT username FROM users;
```

**Reply by TheGorf** [reply]
Negative: 
```
$ docker exec -it web bash
mastodon@1f4cbc90404b:~$ RAILS_ENV=production bundle exec rails dbconsole

Couldn't find database client: psql. Check your $PATH and try again.
```

and if I do a quick find/grep for psql it appears to be not found anywhere.

**Reply by palonza** [reply]
do you can paste your compose file? or docker run command?

**Reply by TheGorf** [reply]
Sure. Nothin special:

```
version: '3'
services:
  db:
    restart: always
    image: postgres:14-alpine
    container_name: db
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - postgres14_41:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  redis:
    restart: always
    image: redis:7-alpine
    container_name: redis
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - redis:/data

  # es:
  #   restart: always
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true"
  #     - "xpack.license.self_generated.type=basic"
  #     - "xpack.security.enabled=false"
  #     - "xpack.watcher.enabled=false"
  #     - "xpack.graph.enabled=false"
  #     - "xpack.ml.enabled=false"
  #     - "bootstrap.memory_lock=true"
  #     - "cluster.name=es-mastodon"
  #     - "discovery.type=single-node"
  #     - "thread_pool.write.queue_size=1000"
  #   networks:
  #      - external_network
  #      - internal_network
  #   healthcheck:
  #      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
  #   volumes:
  #      - ./elasticsearch:/usr/share/elasticsearch/data
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   ports:
  #     - '127.0.0.1:9200:9200'

  web:
    build: .
    image: ghcr.io/mastodon/mastodon
    container_name: web
    restart: always
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - external_network
      - internal_network
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
      # - es
    volumes:
      - mastodon_system:/mastodon/public/system

  streaming:
    build: .
    image: ghcr.io/mastodon/mastodon
    container_name: streaming
    restart: always
    env_file: .env.production
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']
    ports:
      - '4000:4000'
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    image: ghcr.io/mastodon/mastodon
    container_name: sidekiq
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - mastodon_system:/mastodon/public/system
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]

  console:
    image: ghcr.io/mastodon/mastodon
    container_name: console
    env_file: .env.production
    command: /bin/bash
    restart: "no"
    depends_on:
      - db
      - redis
    networks:
      - internal_network
      - external_network
    volumes:
      - mastodon_system:/mastodon/public/system

  ## Uncomment to enable federation with tor instances along with adding the following ENV variables
  ## http_proxy=http://privoxy:8118
  ## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
  # tor:
  #   image: sirboops/tor
  #   networks:
  #      - external_network
  #      - internal_network
  #
  # privoxy:
  #   image: sirboops/privoxy
  #   volumes:
  #     - ./priv-config:/opt/config
  #   networks:
  #     - external_network
  #     - internal_network


volumes:
  postgres14_41:
    driver: local
    name: postgres14
  redis:
    driver: local
    name: redis
  mastodon_system:
    driver: local
    name: mastodon_system

networks:
  internal_network:
    internal: true
    name: internal_network
  external_network:
    name: external_network

```
