### DISCUSSION TITLE
Custom SCSS not fully working

### DISCUSSION THREAD

**Discussion by KaitoCross** [mastodon/mastodon#27913] [General]
### What I've tried to do
I copied the mastodon-light theme, renamed the copy and just adjusted some colors.
I integrated the theme according to the instructions on https://github.com/tootsuite/documentation/blob/archive/Running-Mastodon/Customizing.md

variables.scss:
```scss
// Dependent colors
$black: #006600;
$white: #6e966e;

$classic-base-color: #336600;
$classic-primary-color: #00802b;
$classic-secondary-color: #000000;
$classic-highlight-color: #003300;

// Differences
$success-green: lighten(#3c754d, 8%);

$base-overlay-background: $white !default;
$valid-value-color: $success-green !default;

$ui-base-color: $classic-secondary-color !default;
$ui-base-lighter-color: #009933;
$ui-primary-color: #66ff66;
$ui-secondary-color: $classic-base-color !default;
$ui-highlight-color: #00cc00;

$primary-text-color: $black !default;
$darker-text-color: $classic-base-color !default;
$dark-text-color: $black !default;
$action-button-color: #606984;

$inverted-text-color: $black !default;
$lighter-text-color: $classic-base-color !default;
$light-text-color: $white !default;

//Newly added colors
$account-background-color: #000000;

//Invert darkened and lightened colors
@function darken($color, $amount) {
  @return hsl(hue($color), saturation($color), lightness($color) + $amount);
}

@function lighten($color, $amount) {
  @return hsl(hue($color), saturation($color), lightness($color) - $amount);
}
```

### Expected behaviour
All colors should have changed

### Actual behaviour

In advanced mode, all colors chance except of the widgets colors. the widgets keep their white background color, even though I never configured any #FFFFFF in my scss. Deleting the contents of public/packs and then recompiling the assets & restarting Mastodon doesnt help.

### Specifications
Browser: Latest Arch Linux with Firefox 72
Mastodon Version: 3.0.1
