### DISCUSSION TITLE
Mastadon - Error Connecting To Database: relation accounts does not exist

### DISCUSSION THREAD

**Discussion by JHenzi** [mastodon/mastodon#27937] [General]
### Expected behaviour: 

Connection to database from inside container is seamless

### Actual behaviour

`web_1        | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/pg-1.2.3/lib/pg.rb:58:in `initialize': could not connect to server: No such file or directory (PG::ConnectionBad)
web_1        |  Is the server running locally and accepting
web_1        |  connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
`

### Steps to reproduce the problem

Build tootsuite from docker compose here (after setting environment details): https://github.com/tootsuite/mastodon

### Specifications

Latest, if needed can paste Docker Compose

Have read some guides, PG setup should be not needed, though have set in compose and in the environment variables a password and no password. All containers share the local network.

**Comment by JHenzi** [comment]
I see there used to be a Production Guide - where is this now? All the links to it are dead.

**Comment by JHenzi** [comment]
I can now connect, I figured out the issue. But now I get a real specific error to the code;

`ERROR:  relation "accounts" does not exist at character 566`

**Comment by iot-resister** [comment]
@jhenzi  I'm having the same error. Did you ever get anywhere on this?

```
| ERROR:  relation "accounts" does not exist at character 566
| STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttyp

|                            pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.

|                            c.collname, col_description(a.attrelid, a.attnum)

|                       FROM pg_attribute a
|                       LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a

|                       LEFT JOIN pg_type t ON a.atttypid = t.oid
|                       LEFT JOIN pg_collation c ON a.attcollation = c.oid AND

|                      WHERE a.attrelid = '"accounts"'::regclass
|                        AND a.attnum > 0 AND NOT a.attisdropped
|                      ORDER BY a.attnum
```

```yml
version: '3'

volumes:
  mastodon:

services:
  mastodon:
    image: tootsuite/mastodon
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - mastodon:/mastodon/public/system
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: 192.168.0.14
      REDIS_PORT: 6379
      DB_HOST: 192.168.0.14
      DB_USER: $DEV_NAME
      DB_NAME: mastodon
      DB_PASS: $POSTGRES_PW
      DB_PORT: 5432
      OTP_SECRET: $OTP_SECRET
      SECRET_KEY_BASE: $SECRET_KEY_BASE
```

**Comment by Gargron** [comment]
Possibly outdated Docker guide: https://github.com/tootsuite/documentation/blob/archive/Running-Mastodon/Docker-Guide.md

Up-to-date installation guide for a normal (non-Docker) setup: https://docs.joinmastodon.org/admin/install/

The gist is that you've likely not run any setup command so your database is completely blank. You may missing other configuration too, for example, if the above comment is all environment variables you've got, you're missing many required ones, the structure also doesn't look too familiar, Mastodon already comes with a docker-compose.yml file that's a good template.

**Comment by iot-resister** [comment]
@Gargron Still no luck following the guide. 

Here's my issue for what its worth

https://discourse.joinmastodon.org/t/docker-setup-error-domain-name/2051

**Comment by JHenzi** [comment]
I was able to run the setup in docker which removed the issue, corrected docker to look at "db" as host instead of running in /var and I got as far as getting a too many redirects issue. I'm unsure how to resolve that one.

**Comment by thomasmarkiewicz** [comment]
I ran into that same issue while trying to setup Mastodon on my minikube Kubernetes cluster. 

I resolved it by first manually starting the Mastodon deployment with a fake command that runs forever:
```
command:
  - bash
args:   
  - -c
  - while :; do echo 'Hit CTRL+C'; sleep 1; done
```

That allowed the Pod to startup up successfully so that I could manually shell into it with
```
kubectl get pods
kubectl exec -it <pod name> -- sh
```

Once in the container, I verified the running user is `mastodon` with
```
whoami
```

And ran the following command to do the initial setup (generate .env.production and setup db schema) See: https://docs.joinmastodon.org/admin/install/
```
RAILS_ENV=production bundle exec rake mastodon:setup
```

I guess this needs to be done manually once to generate the initial db schema.  It would be nice if the docker image could somehow detect that the db doesn't have a schema yet and generate it automatically, but that doesn't appear to be the case.

Anyway, after that my Pod is at least staying up (I haven't checked if it actually works yet - still need some more k8s configs before I get there).

Here is my k8s for Mastodon-web deployment in case that helps anyone:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mastodon-web
  template:
    metadata:
      labels:
        component: mastodon-web
    spec:
      volumes:
        - name: mastodon-web-storage
          persistentVolumeClaim:
            claimName: mastodon-web-persistent-volume-claim
      containers:
        - name: mastodon-web
          image: tootsuite/mastodon:v3.2.1
          command:
            - bash
          # args:
          #   - -c
          #  - while :; do echo 'Hit CTRL+C'; sleep 1; done
          args:
            - -c
            - rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000
          ports:
            - containerPort: 3000 # see above 'args' - we start on port 3000
          volumeMounts:
            - name: mastodon-web-storage
              mountPath: /mastodon/public/system
          env:
            - name: DB_HOST
              value: mastodon-postgres-cluster-ip-service
            - name: DB_NAME  # Q: secret?
              value: mastodon
            - name: DB_USER # Q: secret?
              value: mastodon
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_PORT
              value: '5432'
            - name: ES_ENABLED
              value: 'false'
            - name: LOCAL_DOMAIN
              value: something.com # TODO: update to new value
            - name: OTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: OTP_SECRET
            - name: REDIS_HOST
              value: mastodon-redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: SAFETY_ASSURED
              value: '1'
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: SECRET_KEY_BASE
            - name: SMTP_FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: SMTP_FROM_ADDRESS
            - name: SMTP_LOGIN
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: SMTP_LOGIN
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: SMTP_PASSWORD
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: SMTP_PORT
            - name: SMTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: SMTP_SERVER           
            - name: STREAMING_CLUSTER_NUM
              value: '1'

```
