### DISCUSSION TITLE
Can't login or sign up

### DISCUSSION THREAD

**Discussion by artichoked1** [mastodon/mastodon#28309] [Q&A]
Just done a fresh install of Mastodon on my k8s cluster through the official helm chart. I'm using an external postgres cluster and redis cluster.
Everything installs fine and all pods are healthy, but when I click the signup button or attempt the click the login button after entering my email and password, I just get a generic `We're sorry, but something went wrong on our end` error.

Upon looking at the logs of the `mastodon-web` container, I see the following for when a get request to the signup page is made:
```
[69fa3fbc-55a3-4abc-95a5-fb22b5d20581] method=GET path=/auth/sign_up format=html controller=Auth::RegistrationsController action=new status=500 error='NoMethodError: undefined method `sign_up_ip=' for #<User email: "", created_at: nil, updated_at: nil, admin: false, locale: "en", encrypted_otp_secret: nil, encrypted_otp_secret_iv: nil, encrypted_otp_secret_salt: nil, consumed_timestep: nil, otp_required_for_login: false, last_emailed_at: nil, otp_backup_codes: nil, account_id: nil, id: nil, otp_secret: nil>
2023-12-10T14:10:05.235213300+10:30 Did you mean?  sign_in_count=' duration=127.49 view=0.00 db=2.93
```
and when I try to sign in:
```
[33da58b2-4307-42e3-b02d-27358726d44e] method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=create status=500 error='ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column accounts.silenced does not exist
2023-12-10T14:14:38.371737915+10:30 LINE 1: ...ader_updated_at", "accounts"."avatar_remote_url", "accounts"...
                                                             ^
HINT:  Perhaps you meant to reference the column "accounts.silenced_at".
2023-12-10T14:14:38.371798090+10:30 ' duration=198.90 view=0.00 db=4.89
[33da58b2-4307-42e3-b02d-27358726d44e]   
2023-12-10T14:14:38.373413131+10:30 [33da58b2-4307-42e3-b02d-27358726d44e] ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column accounts.silenced does not exist
2023-12-10T14:14:38.373437387+10:30 LINE 1: ...ader_updated_at", "accounts"."avatar_remote_url", "accounts"...
2023-12-10T14:14:38.373541822+10:30                                                              ^
2023-12-10T14:14:38.373564165+10:30 HINT:  Perhaps you meant to reference the column "accounts.silenced_at".
```

As these seemed to look like database errors, I checked that the migrations job was getting run successfully, and even tried reinstalling the postgres cluster (I'm using cloudnative-pg).

Here is a copy of my helm values file with sensitive information taken out:
```yaml
affinity: {}
deploymentAnnotations: {}
elasticsearch:
  global:
    storageClass: 'hdd-array-local'
  master:
    persistence:
      storageClass: 'hdd-array-local'
  data:
    persistence:
      storageClass: 'hdd-array-local'
  enabled: true
  image:
    tag: latest
externalAuth:
  cas:
    enabled: false
  ldap:
    enabled: false
  oauth_global:
    omniauth_only: false
  oidc:
    enabled: true
    display_name: "artichoke-technologies"
    issuer: 'https://auth.REDACTED.com/application/o/mastodon/'
    discovery: true
    scope: "openid,profile"
    client_id: REDACTED
    client_secret: REDACTED
    redirect_uri: https://mastodon.REDACTED.com/auth/auth/openid_connect/callback
  pam:
    enabled: false
  saml:
    enabled: false
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/mastodon/mastodon
  tag: ''
ingress:
  annotations:
    cert-manager.io/cluster-issuer: "acme-issuer"
  enabled: true
  hosts:
    - host: mastodon.REDACTED.com
      paths:
        - path: /
    - host: REDACTED.com
      paths:
        - path: /.well-known/webfinger
  ingressClassName: null
  tls:
    - hosts:
        - mastodon.REDACTED.com
        - REDACTED.com
      secretName: REDACTED-com-wildcard
jobAnnotations: {}
mastodon:
  authorizedFetch: false
  createAdmin:
    email: REDACTEDtricknp@gmail.com
    enabled: true
    username: artichoke
  cron:
    removeMedia:
      enabled: true
      schedule: 0 0 * * 0
  limitedFederationMode: false
  local_domain: REDACTED.com
  locale: en
  metrics:
    statsd:
      address: ''
  persistence:
    assets:
      accessMode: ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    system:
      accessMode: ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
  preparedStatements: true
  s3:
    access_key: ''
    access_secret: ''
    alias_host: ''
    bucket: ''
    enabled: false
    endpoint: ''
    existingSecret: ''
    hostname: ''
    permission: ''
    region: ''
  secrets:
    existingSecret: ''
    otp_secret: 'REDACTED'
    secret_key_base: 'REDACTED'
    vapid:
      private_key: 'REDACTED'
      public_key: 'REDACTED'
  sidekiq:
    affinity: {}
    podSecurityContext: {}
    resources: {}
    securityContext: {}
    workers:
      - affinity: {}
        concurrency: 25
        name: all-queues
        queues:
          - default,8
          - push,6
          - ingress,4
          - mailers,2
          - pull
          - scheduler
        replicas: 1
        resources: {}
  singleUserMode: false
  smtp:
    auth_method: plain
    ca_file: /etc/ssl/certs/ca-certificates.crt
    delivery_method: smtp
    domain: REDACTED.com
    enable_starttls: auto
    existingSecret: null
    from_address: no-reply@REDACTED.com
    login: no-reply@REDACTED.com
    openssl_verify_mode: peer
    password: 'REDACTED'
    port: 587
    reply_to: support@REDACTED.com
    return_path: null
    server: smtp.REDACTED.com
    tls: true
  streaming:
    affinity: {}
    base_url: null
    podSecurityContext: {}
    port: 4000
    replicas: 1
    resources: {}
    securityContext: {}
    workers: 1
  web:
    affinity: {}
    maxThreads: '5'
    minThreads: '5'
    persistentTimeout: '20'
    podSecurityContext: {}
    port: 3000
    replicas: 1
    resources: {}
    securityContext: {}
    workers: '2'
  web_domain: mastodon.REDACTED.com
nodeSelector: {}
podAnnotations: {}
podSecurityContext:
  fsGroup: 991
  runAsGroup: 991
  runAsUser: 991
postgresql:
  postgresqlHostname: mastodon-postgres-rw
  postgresqlPort: 5432
  auth:
    database: mastodon
    existingSecret: 'mastodon-postgres-password'
    password: ''
    username: mastodon
  enabled: false
redis:
  auth:
    password: ''
  enabled: false
  hostname: 'rfrm-mastodon-redis'
  port: 6379
resources: {}
revisionPodAnnotation: true
securityContext: {}
service:
  port: 80
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: ''
tolerations: []
```
