### DISCUSSION TITLE
My server isn't working as expected...

### DISCUSSION THREAD

**Discussion by sadorowo** [mastodon/mastodon#29788] [Q&A]
So... yesterday I created my server. Almost everything was working fine, except SMTP and sidekiq.
Today I decided to create everything from scratch - so I:
1. Deleted Mastodon Docker files and images
2. Cloned repo again
3. Configured my new server with the same domain

I got SMTP to work, but sidekiq is still holding items in queue - it's connected to my Redis, but it doesn't process the items.

But, there's another issue.
After logging in using my admin account, I see this:
![Zrzut ekranu 2024-03-28 o 13 25 49](https://github.com/mastodon/mastodon/assets/97941280/7b2d3757-cdbd-419e-b16c-70afc33eaf7a)

That means:
"Your application is waiting for us to approve it. This may take some time. If your application is approved, you will receive an email."

I have one e-mail in Sidekiq queue, but it is there because I changed my admin password to my custom one.

Please help me, I'm a newbie and I don't know what I've done wrong.
Sidekiq dashboard:
![Zrzut ekranu 2024-03-28 o 12 58 29](https://github.com/mastodon/mastodon/assets/97941280/a4146261-3f1f-4f34-a794-48b94efb14ea)

My .env content:
```
LOCAL_DOMAIN=social.sador.me
SINGLE_USER_MODE=false
SECRET_KEY_BASE=<redacted>
OTP_SECRET=<redacted>
VAPID_PRIVATE_KEY=<redacted>
VAPID_PUBLIC_KEY=<redacted>
DB_HOST=db
DB_PORT=5432
DB_NAME=mastodon
DB_USER=mastodon
DB_PASS=<redacted>
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=
SMTP_SERVER=mail.sador.me
SMTP_PORT=587
SMTP_LOGIN=<redacted>
SMTP_PASSWORD=<redacted>
SMTP_AUTH_METHOD=plain
SMTP_OPENSSL_VERIFY_MODE=peer
SMTP_ENABLE_STARTTLS=always
SMTP_FROM_ADDRESS=<redacted>
```

My docker-compose.yml content:
```yaml
version: '3'
services:
  db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./postgres14:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis:/data

  es:
     restart: always
     image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
     environment:
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true"
       - "xpack.license.self_generated.type=basic"
       - "xpack.security.enabled=false"
       - "xpack.watcher.enabled=false"
       - "xpack.graph.enabled=false"
       - "xpack.ml.enabled=false"
       - "bootstrap.memory_lock=true"
       - "cluster.name=es-mastodon"
       - "discovery.type=single-node"
       - "thread_pool.write.queue_size=1000"
     networks:
        - external_network
        - internal_network
     healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
     volumes:
        - ./elasticsearch:/usr/share/elasticsearch/data
     ulimits:
       memlock:
         soft: -1
         hard: -1
       nofile:
         soft: 65536
         hard: 65536
     ports:
       - '9200'

  web:
    #build: .
    image: tootsuite/mastodon:latest
    restart: always
    env_file: .env.production
    command: bundle exec puma -C config/puma.rb
    networks:
      - external_network
      - internal_network
      - caddy
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    ports:
      - '3000'
    depends_on:
      - db
      - redis
      - es
    volumes:
      - ./public/system:/mastodon/public/system

  streaming:
    #build: .
    image: tootsuite/mastodon:latest
    restart: always
    env_file: .env.production
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']
    ports:
      - '4000'
    depends_on:
      - db
      - redis

  sidekiq:
    #build: .
    image: tootsuite/mastodon:latest
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]

  ## Uncomment to enable federation with tor instances along with adding the following ENV variables
  ## http_hidden_proxy=http://privoxy:8118
  ## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
  # tor:
  #   image: sirboops/tor
  #   networks:
  #      - external_network
  #      - internal_network
  #
  # privoxy:
  #   image: sirboops/privoxy
  #   volumes:
  #     - ./priv-config:/opt/config
  #   networks:
  #     - external_network
  #     - internal_network

networks:
  external_network:
  internal_network:
    internal: true
  caddy:
    external: true
```

Note: I'm using Caddy for proxying Mastodon into my domain. Configuration was good.
