### DISCUSSION TITLE
Cannot create account on self hosted Mastodon

### DISCUSSION THREAD

**Discussion by SardineFish** [mastodon/mastodon#30264] [Q&A]
I setup a mastodon server using the official docker image. But cannot create any account on web with a message "Creating an account on xxxxx is currently not possible". I searched for this but get nothing help. 

I also used `docker-compose run --rm mastodon bundle exec rake mastodon:setup` to setup the server and database. But crash on the step to create admin user.

```
...

Redis host: redis
Redis port: 6379
Redis password:
Redis configuration works!

...

Do you want to create an admin user straight away? Yes
Username: admin
E-mail: xxxx@xxxx.xxx
rake aborted!
Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)

...
```

It seems to connect redis on `127.0.0.1:6379` but I had configured the redis at `redis:6379` in docker network.

My `docker-compose.yml`

```yaml
services:
  db:
    image: postgres:14-alpine
    container_name: mastodon_db
    environment:
      POSTGRES_USER: mastodon
      POSTGRES_PASSWORD: mastodon
      POSTGRES_DB: mastodon
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: "trust"
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    shm_size: 128mb
    volumes:
      - /path/to/mastodon/data:/var/lib/postgresql/data/pgdata
  redis:
    container_name: mastodon_redis
    image: redis:6-alpine
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - /path/to/mastodon/redis/data:/data
      - /path/to/mastodon/redis/config:/usr/local/etc/redis
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    restart: unless-stopped
  mastodon:
    image: ghcr.io/mastodon/mastodon:nightly.2024-05-11
    container_name: mastodon
    command: bundle exec puma -C config/puma.rb
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    links:
      - db:db
      - redis:redis
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db
      - DB_USER=mastodon
      - DB_NAME=mastodon
      - DB_PASS=mastodon
      - DB_PORT=5432
      - ES_ENABLED=false
      - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=xxxxxxxxxxx
      - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=xxxxxxxxxxx
      - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=xxxxxxxxxxx
      - SECRET_KEY_BASE=xxxxxxxxxxxxxxxx
      - OTP_SECRET=xxxxxxxxxxxxxxx
      - VAPID_PRIVATE_KEY=xxxxxxxxxxxx
      - VAPID_PUBLIC_KEY=xxxxxxxxxxxxxxx
      - SMTP_SERVER=xxxxxxxxxxxxxx
      - SMTP_PORT=xxxxx
      - SMTP_LOGIN=xxxxxxxxxxxxxx
      - SMTP_PASSWORD=xxxxxxxxxxxxx
      - SMTP_FROM_ADDRESS=xxxxxxxxxxxxxx
      - SMTP_TLS=true
      - S3_ENABLED=false
      - WEB_DOMAIN=xxxxx
      - LOCAL_DOMAIN=xxxxx
      - SINGLE_USER_MODE=false
    volumes:
      - /path/to/mastodon/config:/config
    ports:
      - 127.0.0.1:xxxx:3000
    restart: unless-stopped
networks:
  default:
    external: true
    name: mastodon_net
```
