### DISCUSSION TITLE
(Docker) node and nodejs not found

### DISCUSSION THREAD

**Discussion by th0mcat** [mastodon/mastodon#32722] [General]
When trying to [install Tangerine UI on my `glitch-soc` docker container](https://github.com/nileane/TangerineUI-for-Mastodon?tab=readme-ov-file#installation-for-glitch-soc-admins), I get the following:

```bash
[10:00:26] user@server:~$ docker exec -e RAILS_ENV=production -u root -it mastodon_web bundle exec rails assets:precompile
sh: 1: node: not found
sh: 1: nodejs: not found
Node.js not installed. Please download and install Node.js https://nodejs.org/en/download/
Exiting!
```

Here is the relevant section from my `docker-compose.yaml`:

```yaml
  mastodon_web:
    image: ghcr.io/glitch-soc/mastodon:latest
    container_name: mastodon_web
    hostname: mastodon_web
    restart: unless-stopped
    env_file: /<path>/opt/mastodon/.docker.env
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    volumes:
      - /<path>/opt/mastodon/public/system:/mastodon/public/system
      - /<path>/opt/mastodon/TangerineUI-for-Mastodon/mastodon/app/javascript/styles:/opt/mastodon/app/javascript/styles:rw
```

I can install nodejs using `apt`, but I figured it would have already been installed.  Running the same command on the `mastodon_streaming` container results in:

```bash
[10:11:21] user@server:~$ docker exec -e RAILS_ENV=production -it mastodon_streaming bundle exec rails assets:precompile
OCI runtime exec failed: exec failed: unable to start container process: exec: "bundle": executable file not found in $PATH: unknown
``` 

Am I doing this wrong?
