### ISSUE TITLE
Mail SMTP ovh SSL

### ISSUE THREAD

**Issue by shiipou** [mastodon/mastodon#13240]
<!-- Make sure that you are submitting a new bug that was not previously reported or already fixed -->

<!-- Please use a concise and distinct title for the issue -->

### Expected behaviour

<!-- What should have happened? -->
Send email when user has registred.

### Actual behaviour

<!-- What happened? -->

No email was send, request was stuck in sidekiq and say error 535 5.7.1 Authentication failed

sidekiq container logs say that :

```
mastodon_sidekiq.1.hppplvoll7q5@nocturlab-tower    | 2020-03-09T20:28:36.695Z 6 TID-ov4h9i0i2 ActionMaile                                                                                                                                                                                                                     r::DeliveryJob JID-493484914e3e08f17259c047 INFO: fail: 1.302 sec
mastodon_sidekiq.1.dcmcw9jwsflm@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/rails.rb:42:in `call'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activejo                                                                                                                                                                                                                     b-5.2.3/lib/active_job/logging.rb:46:in `tag_logger'
mastodon_sidekiq.1.t8rw8p8u5f46@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
mastodon_sidekiq.1.dcmcw9jwsflm@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
mastodon_sidekiq.1.t8rw8p8u5f46@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activejo                                                                                                                                                                                                                     b-5.2.3/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
mastodon_sidekiq.1.hppplvoll7q5@nocturlab-tower    | 2020-03-09T20:28:36.695Z 6 TID-ov4h9i0i2 WARN: {"con                                                                                                                                                                                                                     text":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapp                                                                                                                                                                                                                     ed":"ActionMailer::DeliveryJob","queue":"mailers","args":[{"job_class":"ActionMailer::DeliveryJob","job_i                                                                                                                                                                                                                     d":"cf62a71a-174c-4bbe-8965-befb2b49522d","provider_job_id":null,"queue_name":"mailers","priority":null,"                                                                                                                                                                                                                     arguments":["UserMailer","confirmation_instructions","deliver_now",{"_aj_globalid":"gid://mastodon/User/1                                                                                                                                                                                                                     "},"NtbynG5SfhyBx27tsKmp",{"_aj_symbol_keys":[]}],"executions":0,"locale":"fr"}],"retry":true,"jid":"4934                                                                                                                                                                                                                     84914e3e08f17259c047","created_at":1583683981.8581443,"enqueued_at":1583785715.3926582,"error_message":"5                                                                                                                                                                                                                     35 5.7.1 Authentication failed\n","error_class":"Net::SMTPAuthenticationError","failed_at":1583683983.048                                                                                                                                                                                                                     9466,"retry_count":13,"retried_at":1583785461.3236706},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::S                                                                                                                                                                                                                     idekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::DeliveryJob\",\"queue\":\"mailers\",\"args\":[{\"                                                                                                                                                                                                                     job_class\":\"ActionMailer::DeliveryJob\",\"job_id\":\"cf62a71a-174c-4bbe-8965-befb2b49522d\",\"provider_                                                                                                                                                                                                                     job_id\":null,\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"UserMailer\",\"confirmation_i                                                                                                                                                                                                                     nstructions\",\"deliver_now\",{\"_aj_globalid\":\"gid://mastodon/User/1\"},\"NtbynG5SfhyBx27tsKmp\",{\"_a                                                                                                                                                                                                                     j_symbol_keys\":[]}],\"executions\":0,\"locale\":\"fr\"}],\"retry\":true,\"jid\":\"493484914e3e08f17259c0                                                                                                                                                                                                                     47\",\"created_at\":1583683981.8581443,\"enqueued_at\":1583785715.3926582,\"error_message\":\"535 5.7.1 Authentication failed\\n\",\"error_class\":\"Net::SMTPAuthenticationError\",\"failed_at\":1583683983.04894                                                                                                                                                                                                                     66,\"retry_count\":13,\"retried_at\":1583785461.3236706}"}
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activejo                                                                                                                                                                                                                     b-5.2.3/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/callbacks.rb:118:in `instance_exec'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/callbacks.rb:136:in `run_callbacks'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activejo                                                                                                                                                                                                                     b-5.2.3/lib/active_job/execution.rb:38:in `perform_now'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activejo                                                                                                                                                                                                                     b-5.2.3/lib/active_job/execution.rb:24:in `block in execute'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activejo                                                                                                                                                                                                                     b-5.2.3/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/reloader.rb:73:in `block in wrap'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/execution_wrapper.rb:83:in `wrap'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/reloader.rb:72:in `wrap'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activejo                                                                                                                                                                                                                     b-5.2.3/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/callbacks.rb:118:in `instance_exec'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/callbacks.rb:136:in `run_callbacks'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activejo                                                                                                                                                                                                                     b-5.2.3/lib/active_job/execution.rb:22:in `execute'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activejo                                                                                                                                                                                                                     b-5.2.3/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/processor.rb:192:in `execute_job'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/processor.rb:165:in `block (2 levels) in process'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/app/lib/sidekiq_error_handler.rb:5:in                                                                                                                                                                                                                      `call'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     unique-jobs-6.0.13/lib/sidekiq_unique_jobs/server/middleware.rb:29:in `call'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/middleware/chain.rb:133:in `invoke'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/processor.rb:164:in `block in process'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/job_retry.rb:109:in `local'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/rails.rb:43:in `block in call'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/reloader.rb:73:in `block in wrap'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesu                                                                                                                                                                                                                     pport-5.2.3/lib/active_support/reloader.rb:72:in `wrap'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/rails.rb:42:in `call'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/processor.rb:250:in `stats'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-                                                                                                                                                                                                                     5.2.7/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_logger.rb:8:in `call'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_retry.rb:74:in `global'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:125:in `block in dispatch'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:48:in `with_context'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:124:in `dispatch'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:163:in `process'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:83:in `process_one'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:71:in `run'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:16:in `watchdog'
mastodon_sidekiq.1.xdo7uz6dleny@nocturlab-tower    | /opt/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'

```
### Steps to reproduce the problem

<!-- What were you trying to do? -->

I try to launch my instance of Mastodon but registration mail does not work with my OVH mail server.

I use this docker stack file : 

```
version: "3.7"

services:

  redis:
    image: redis:5.0-alpine
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    deploy:
      replicas: 1
    volumes:
      - redis:/data

  web:
    image: tootsuite/mastodon
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db.nocturlab.fr
      - DB_USER=mastodon
      - DB_NAME=mastodon
      - DB_PASS=******
      - DB_PORT=5432
      - LOCAL_DOMAIN=mastodon.nocturlab.fr
      - WEB_DOMAIN=mastodon.nocturlab.fr
      - SECRET_KEY_BASE=******
      - OTP_SECRET=******
      - VAPID_PRIVATE_KEY=******
      - VAPID_PUBLIC_KEY=*******
      - DEFAULT_LOCALE=fr
      - SMTP_SERVER=${SMTP_HOSTNAME:-ssl0.ovh.net}
      - SMTP_PORT=${SMTP_PORT:-465}
      - SMTP_LOGIN=${SMTP_USERNAME:-postmaster@nocturlab.fr}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-******}
      - SMTP_FROM_ADDRESS=${SMTP_FROM:-mastodon@nocturlab.fr}
      - SMTP_DOMAIN=nocturlab.fr
      - SMTP_TLS=${SMTP_TLS:-true}
      - SMTP_ENABLE_STARTTLS_AUTO=true
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    deploy:
      labels:
        ###          ###
        # Mastodon Web #
        ###          ###

        ##
        # Service
        #
        # Enable this endpoint
        - "traefik.enable=true"
        # Set the service port
        - "traefik.http.services.mastodon.loadbalancer.server.port=3000"
        #
        ##

        ##
        # Http
        #
        # Set the service route
        - "traefik.http.routers.mastodon-http.rule=Host(`mastodon.nocturlab.fr`)"
        # Set the entrypoint (http or https)
        - "traefik.http.routers.mastodon-http.entrypoints=http"
        # Rule to redirect to http to https
        - "traefik.http.middlewares.mastodon-https-redirect.redirectscheme.scheme=https"
        # Enable Https redirection
        - "traefik.http.routers.mastodon-http.middlewares=mastodon-https-redirect@docker"
        #
        ##

        ##
        # Https
        #
        # Set the service route
        - "traefik.http.routers.mastodon-https.rule=Host(`mastodon.nocturlab.fr`)"
        # Set the entrypoint (http or https)
        - "traefik.http.routers.mastodon-https.entrypoints=https"
        # Enable Let's encrypt auto certificat creation
        - "traefik.http.routers.mastodon-https.tls.certresolver=certbot"
        #
        ##
      replicas: 1
    networks:
      - ingress_net
      - internal
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
    volumes:
      - system:/mastodon/public/system

  streaming:
    image: tootsuite/mastodon
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db.nocturlab.fr
      - DB_USER=mastodon
      - DB_NAME=mastodon
      - DB_PASS=******
      - DB_PORT=5432
      - LOCAL_DOMAIN=mastodon.nocturlab.fr
      - WEB_DOMAIN=mastodon.nocturlab.fr
      - SECRET_KEY_BASE=******
      - OTP_SECRET=******
      - VAPID_PRIVATE_KEY=******
      - VAPID_PUBLIC_KEY=******
      - DEFAULT_LOCALE=fr
      - SMTP_SERVER=${SMTP_HOSTNAME:-ssl0.ovh.net}
      - SMTP_PORT=${SMTP_PORT:-465}
      - SMTP_LOGIN=${SMTP_USERNAME:-postmaster@nocturlab.fr}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-******}
      - SMTP_FROM_ADDRESS=${SMTP_FROM:-mastodon@nocturlab.fr}
      - SMTP_DOMAIN=nocturlab.fr
      - SMTP_TLS=${SMTP_TLS:-true}
      - SMTP_ENABLE_STARTTLS_AUTO=true
    command: node ./streaming
    deploy:
      labels:
        ###             ###
        # Mastodon Stream #
        ###             ###

        ##
        # Service
        #
        # Enable this endpoint
        - "traefik.enable=true"
        # Set the service port
        - "traefik.tcp.services.mastodon.loadbalancer.server.port=4000"
        #
        ##

        ##
        # 4000
        #
        # Set the service route
        - "traefik.tcp.routers.mastodon.rule=HostSNI(`*`)"
        # Set the entrypoin
        - "traefik.tcp.routers.mastodon.entrypoints=mastodon"
        #
        ##
      replicas: 1
    networks:
      - ingress_net
      - internal
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1"]

  sidekiq:
    image: tootsuite/mastodon
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db.nocturlab.fr
      - DB_USER=mastodon
      - DB_NAME=mastodon
      - DB_PASS=******
      - DB_PORT=5432
      - LOCAL_DOMAIN=mastodon.nocturlab.fr
      - WEB_DOMAIN=mastodon.nocturlab.fr
      - SECRET_KEY_BASE=******
      - OTP_SECRET=******
      - VAPID_PRIVATE_KEY=******
      - VAPID_PUBLIC_KEY=*****
      - DEFAULT_LOCALE=fr
      - SMTP_SERVER=${SMTP_HOSTNAME:-ssl0.ovh.net}
      - SMTP_PORT=${SMTP_PORT:-465}
      - SMTP_LOGIN=${SMTP_USERNAME:-postmaster@nocturlab.fr}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-******}
      - SMTP_FROM_ADDRESS=${SMTP_FROM:-mastodon@nocturlab.fr}
      - SMTP_DOMAIN=nocturlab.fr
      - SMTP_TLS=${SMTP_TLS:-true}
      - SMTP_ENABLE_STARTTLS_AUTO=true
    command: bundle exec sidekiq
    deploy:
      replicas: 1
    networks:
      - ingress_net
      - internal
      - db
    volumes:
      - system:/mastodon/public/system

volumes:
  system:
  redis:

networks:
  internal:
  redis:
  ingress_net:
    external: true
  db:
    external: true
    name: db_db
```

### Specifications

<!-- What version or commit hash of Mastodon did you find this bug in? -->
tootsuite/mastodon (v3.0.2)

<!-- If a front-end issue, what browser and operating systems were you using? -->
