### ISSUE TITLE
make a way to have a larger Toot text field, and/or a way to adjust column width in advanced view.

### ISSUE THREAD

**Issue by saadjsct** [mastodon/mastodon#13875]

**Comment by M4rotte** [comment]
I second this one. It would be nice if whatever the number of columns is, the whole thing could use all the available width. It would permit to show more content.

Also, concerning the toot text field width, I think it could be nice to have an horizontal (top or bottom) main menu (which is currently display on the left, before the custom columns.

I didn’t manage to get it this way, although it should be doable at CSS level ?

I just made the following addition in my userContent.css, it works as I want, but for a “one column” only dashboard (and for a particular screen width) :

```css
@-moz-document domain("mamot.fr") {
 body {
  font-size: 1em;
  line-height: 1.5;
  }
 .column {
  width: 1620px !important;
 }
 .drawer {
  width: 1620px;
 }
 .autosuggest-textarea__textarea {
  font-size: 1em;
  min-height: 25em;
 }
}
```

I don’t know if this is possible to use a % of the available parent object width (what class ? .column ? .drawer ?). Any advice appreciated !

I take advantage of this first feature request to thank all the developers of the Mastodon software, which I find really nice at first sight.
