### ISSUE TITLE
Mastodon stops showing images after restart

### ISSUE THREAD

**Issue by LinAGKar** [mastodon/mastodon#16133]
I have Mastodon, and some other things, running in Docker, with a docker-compose.yml looking like this (with non-Mastodon things removed):

```yaml
version: '3.4'

volumes:
  mastodon-db:
  mastodon-db-sock:
  mastodon-system:
  acme-challenge:
  mastodon-redis:
  mastodon-redis-sock:
  mastodon-html:
  nginx-mastodon-sock:

services:
  mastodon-db:
    image: postgres:13
    restart: unless-stopped
    shm_size: 256mb
    volumes:
      - mastodon-db:/var/lib/postgresql
      - mastodon-db-sock:/var/run/postgresql/
    networks:
      - mastodon-db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    environment:
      - POSTGRES_USER=mastodon
      - POSTGRES_PASSWORD_FILE=/run/secrets/mastodon_db_password
      - POSTGRES_DB=mastodon
      - PGDATA=/var/lib/postgresql/13/data
    secrets:
      - mastodon_db_password

  mastodon-redis:
    build: redis
    restart: unless-stopped
    volumes:
      - mastodon-redis:/data
      - mastodon-redis-sock:/var/run/redis/
    networks:
      - mastodon-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  mastodon-web:
    build: mastodon
    restart: unless-stopped
    env_file:
      - mastodon/mastodon.env
      - mastodon/mastodon-secret.env
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid /var/run/mastodon/web.sock; bundle exec rails s"
    networks:
      mastodon-internet:
        ipv4_address: '192.168.13.3'
    dns:
      - '8.8.8.8'
    environment:
      - SOCKET=/var/run/mastodon/web.sock
    depends_on:
      - mastodon-db
      - mastodon-redis
    volumes:
      - mastodon-db-sock:/var/run/postgresql/:ro
      - mastodon-redis-sock:/var/run/redis/:ro
      - mastodon-system:/mastodon/public/system
      - nginx-mastodon-sock:/var/run/mastodon/
      - mastodon-html:/opt/mastodon/public/

  mastodon-streaming:
    build: mastodon
    restart: unless-stopped
    env_file:
      - mastodon/mastodon.env
      - mastodon/mastodon-secret.env
    command: sh -c "rm -f /var/run/mastodon/streaming.sock; node ./streaming"
    networks:
      mastodon-internet:
        ipv4_address: '192.168.13.4'
    dns:
      - '8.8.8.8'
    environment:
      - SOCKET=/var/run/mastodon/streaming.sock
    depends_on:
      - mastodon-db
      - mastodon-redis
    volumes:
      - mastodon-db-sock:/var/run/postgresql/:ro
      - mastodon-redis-sock:/var/run/redis/:ro
      - nginx-mastodon-sock:/var/run/mastodon/

  mastodon-sidekiq:
    build: mastodon
    restart: unless-stopped
    env_file:
      - mastodon/mastodon.env
      - mastodon/mastodon-secret.env
    command: bundle exec sidekiq
    networks:
      mastodon-internet:
        ipv4_address: '192.168.13.5'
    dns:
      - '8.8.8.8'
    depends_on:
      - mastodon-db
      - mastodon-redis
    volumes:
      - mastodon-db-sock:/var/run/postgresql/:ro
      - mastodon-redis-sock:/var/run/redis/:ro
      - mastodon-system:/mastodon/public/system

  nginx:
    build: nginx
    restart: unless-stopped
    user: nginx
    networks:
      nginx-internet:
        ipv4_address: '192.168.10.2'
    dns:
      - '8.8.8.8'
    volumes:
      - mastodon-html:/var/www/html/mastodon:ro
      - acme-challenge:/var/www/acme:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/tls.conf:/etc/nginx/tls.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
      - ./nginx/certs/:/etc/ssl/nginx/:ro
      - /etc/letsencrypt/live/<domain>/:/etc/letsencrypt/live/<domain>/:ro
      - /etc/letsencrypt/live/<domain>/privkey.pem:/etc/privkey.pem:ro
      - /etc/letsencrypt/archive/<domain>/:/etc/letsencrypt/archive/<domain>/:ro
      - ./dhparam:/etc/dhparam:ro
      - nginx-mastodon-sock:/var/run/mastodon/:ro
    depends_on:
      - mastodon-web
      - mastodon-streaming
      - mastodon-sidekiq

secrets:
  mastodon_db_password:
    file: ./mastodon_db_password.txt

networks:
  mastodon-redis:
    internal: true
  mastodon-db:
    internal: true
  nginx-internet:
    driver: macvlan
    driver_opts:
      parent: eth0.10
    ipam:
      config:
        - subnet: 192.168.10.0/24
  mastodon-internet:
    driver: macvlan
    driver_opts:
      parent: eth0.13
    ipam:
      config:
        - subnet: 192.168.13.0/24

```

Mastodon Dockerfile:

```Dockerfile
FROM tootsuite/mastodon:v3.3.0
USER root
RUN mkdir -p /var/run/mastodon/ && chown mastodon:mastodon /var/run/mastodon/
USER mastodon
```

```nginx
map $http_upgrade $mastodon_connection_upgrade {
    default upgrade;
    '' close;
}

upstream mastodon-web {
    server unix:/var/run/mastodon/web.sock fail_timeout=0;
}

upstream mastodon-streaming {
    server unix:/var/run/mastodon/streaming.sock fail_timeout=0;
}

server {
    listen 8443 ssl http2;
    listen [::]:8443 ssl http2;

    server_name mastodon.<domain>;

    include /etc/nginx/tls.conf;

    keepalive_timeout 70;
    sendfile on;
    client_max_body_size 80m;

    root /var/www/html/mastodon;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        try_files $uri @proxy;
    }

    location ~ ^/(emoji|packs|system/accounts/avatars|system/media_attachments/files) {
        add_header Cache-Control "public, max-age=31536000, immutable";
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains;" always;
        try_files $uri @proxy;
    }

    location /sw.js {
        add_header Cache-Control "public, max-age=0";
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains;" always;
        try_files $uri @proxy;
    }

    location @proxy {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Proxy "";
        proxy_pass_header Server;

        proxy_pass http://mastodon-web;
        proxy_buffering on;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $mastodon_connection_upgrade;

        proxy_cache CACHE;
        proxy_cache_valid 200 7d;
        proxy_cache_valid 410 24h;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        add_header X-Cached $upstream_cache_status;
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains;" always;

        tcp_nodelay on;
    }

    location /api/v1/streaming {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Proxy "";

        proxy_pass http://mastodon-streaming;
        proxy_buffering off;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $mastodon_connection_upgrade;

        tcp_nodelay on;
    }

    error_page 500 501 502 503 504 /500.html;
}
```

However, whenever I restart the server, Mastodon stops displaying image attachments for new Toots. They will still show up correctly on old ones where they had already been loaded, but on new ones there will just be a blurry placeholder. It will then typically start working again if I clear the cache by running `bin/tootctl cache clear` in the mastodon-web container, and then restart the mastodon-web container a few times.
