### ISSUE TITLE
Docker does not respect volume mapping

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [mastodon/mastodon#17286]
### Steps to reproduce the problem

1. Install mastodon using docker-compose
2. Open docker-compose.yml file
3. map a volume to your desired location to save uploaded media at
```yaml
      - /mnt/cloud/MASTODON_DATA:/mastodon/public/assets
```

### Expected behaviour

Uploaded new media files should be where specfied in docker-compose file

### Actual behaviour

New media attachments still getting upload in old folder

### Specifications

Using latest mastodon image
docker ver: 20.10.12
docker-compose: 1.29.2
my docker-compose.yml file:
```yaml
version: '3'
services:

  db:
    restart: always
    image: postgres:9.6-alpine
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    environment:
      - POSTGRES_PASSWORD:x
      - POSTGRES_DB:postgres
      - POSTGRES_DB_HOST:db
      - POSTGRES_USER:postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:6.0-alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./redis:/data

#  es:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m UseAVX=0"
#      - "cluster.name=es-mastodon"
#      - "discovery.type=single-node"
#      - "bootstrap.memory_lock=true"
#    networks:
#      - internal_network
#    healthcheck:
#      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
#    volumes:
#      - ./elasticsearch:/usr/share/elasticsearch/data
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1

  web:
    #build: .
    image: tootsuite/mastodon:latest
    restart: always
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off 192.168.0.101:3000/health || exit 1"]
    ports:
      - "192.168.0.101:3000:3000"
    depends_on:
      - db
      - redis
#      - es
    volumes:
      - ./public/system:/mastodon/public/system
      - /mnt/cloud/MASTODON_DATA:/mastodon/public/assets

  streaming:
    #build: .
    image: tootsuite/mastodon:latest
    restart: always
    env_file: .env.production
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off 192.168.0.101:4000/api/v1/streaming/health || exit 1"]
    ports:
      - "192.168.0.101:4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    #build: .
    image: tootsuite/mastodon:latest
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system
     #- /mnt/cloud/MASTODON_DATA/:/mastodon/public/assets
## Uncomment to enable federation with tor instances along with adding the following ENV variables
## http_proxy=http://privoxy:8118
## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
#  tor:
#    image: sirboops/tor
#    networks:
#      - external_network
#      - internal_network
#
#  privoxy:
#    image: sirboops/privoxy
#    volumes:
#      - ./priv-config:/opt/config
#    networks:
#      - external_network
#      - internal_network

networks:
  external_network:
  internal_network:
    internal: true

```
