### ISSUE TITLE
Mailgun Not Receiving Request To Send Emails

### ISSUE THREAD

**Issue by gzukel** [mastodon/mastodon#17481]
Good Morning,

I have Mastodon running in a Kubernetes pod. I'm trying to use Mailgun as my SMTP server. I searched through issues regarding mailgun and others seem to be having gmail blocking issues. That is not my case. That is not my case because Mailgun provides statistics for emails being sent through its SMTP server and its straight up not even seeing the request to send the email. 

```
SMTP_SERVER=smtp.mailgun.org
SMTP_PORT=587
SMTP_LOGIN=postmaster@mail.idevops.io
SMTP_PASSWORD=9-truncated-for-security
SMTP_AUTH_METHOD=plain
SMTP_FROM_ADDRESS=mastodon@mail.idevops.io
```

This configuration looks correct. It is in my .env.production file in the root directory of the application. 

```
mastodon@mastodon-85ff786f88-hxqvp:~$ ls -lah
total 1.0M
drwxr-xr-x  1 mastodon mastodon   40 Feb  8 15:17 .
drwxr-xr-x  1 root     root       22 Feb  8 05:30 ..
-rw-r--r--  1 mastodon mastodon 6.1K Feb  8 05:23 .DS_Store
-rw-r--r--  1 mastodon mastodon  220 Feb 25  2020 .bash_logout
-rw-r--r--  1 mastodon mastodon 3.7K Feb 25  2020 .bashrc
drwxr-xr-x  2 mastodon mastodon   20 Feb  8 05:28 .bundle
drwxr-xr-x  3 mastodon mastodon   18 Feb  8 05:34 .cache
-rw-r--r--  1 mastodon mastodon 1.1K Feb  8 15:17 .env.production
-rw-r--r--  1 mastodon mastodon    0 Feb  8 05:23 .gitmodules
-rw-r--r--  1 mastodon mastodon  807 Feb 25  2020 .profile
drwxr-xr-x  3 mastodon mastodon   17 Feb  8 05:33 .yarn
-rwxr-xr-x  1 mastodon mastodon  51K Feb  8 05:23 AUTHORS.md
-rwxr-xr-x  1 mastodon mastodon  365 Feb  8 05:23 Aptfile
-rwxr-xr-x  1 mastodon mastodon 207K Feb  8 05:23 CHANGELOG.md
-rwxr-xr-x  1 mastodon mastodon 3.2K Feb  8 05:23 CODE_OF_CONDUCT.md
-rwxr-xr-x  1 mastodon mastodon 2.8K Feb  8 05:23 CONTRIBUTING.md
-rwxr-xr-x  1 mastodon mastodon  369 Feb  8 05:23 Capfile
-rwxr-xr-x  1 mastodon mastodon 4.0K Feb  8 05:23 Dockerfile
-rwxr-xr-x  1 mastodon mastodon 1.8K Feb  8 05:23 FEDERATION.md
-rwxr-xr-x  1 mastodon mastodon 4.0K Feb  8 05:23 Gemfile
-rwxr-xr-x  1 mastodon mastodon  20K Feb  8 05:23 Gemfile.lock
-rwxr-xr-x  1 mastodon mastodon  34K Feb  8 05:23 LICENSE
-rwxr-xr-x  1 mastodon mastodon  452 Feb  8 05:23 Procfile
-rwxr-xr-x  1 mastodon mastodon  234 Feb  8 05:23 Procfile.dev
-rwxr-xr-x  1 mastodon mastodon 5.1K Feb  8 05:23 README.md
-rwxr-xr-x  1 mastodon mastodon  249 Feb  8 05:23 Rakefile
-rwxr-xr-x  1 mastodon mastodon  261 Feb  8 05:23 SECURITY.md
-rwxr-xr-x  1 mastodon mastodon 4.3K Feb  8 05:23 Vagrantfile
drwxr-xr-x 16 mastodon mastodon  226 Feb  8 05:23 app
-rwxr-xr-x  1 mastodon mastodon 3.0K Feb  8 05:23 app.json
-rwxr-xr-x  1 mastodon mastodon 1.4K Feb  8 05:23 babel.config.js
drwxr-xr-x  2 mastodon mastodon  184 Feb  8 05:23 bin
-rwxr-xr-x  1 mastodon mastodon 6.1K Feb  8 05:23 boxfile.yml
drwxr-xr-x  3 mastodon mastodon   22 Feb  8 05:33 build
drwxr-xr-x  3 mastodon mastodon  114 Feb  8 05:23 chart
drwxr-xr-x  6 mastodon mastodon 4.0K Feb  8 05:23 config
-rwxr-xr-x  1 mastodon mastodon  183 Feb  8 05:23 config.ru
-rwxr-xr-x  1 mastodon mastodon  703 Feb  8 05:23 crowdin.yml
drwxr-xr-x  5 mastodon mastodon   87 Feb  8 05:23 db
-rwxr-xr-x  1 mastodon mastodon 3.1K Feb  8 05:23 deployment.yaml.template
drwxr-xr-x  2 mastodon mastodon  118 Feb  8 05:23 dist
-rwxr-xr-x  1 mastodon mastodon 2.8K Feb  8 05:23 docker-compose.yml
-rwxr-xr-x  1 mastodon mastodon  324 Feb  8 05:23 ide-helper.js
drwxr-xr-x 18 mastodon mastodon 4.0K Feb  8 05:23 lib
drwxr-xr-x  2 mastodon mastodon   41 Feb  8 05:23 log
drwxr-xr-x  2 mastodon mastodon   85 Feb  8 05:23 nanobox
drwxr-xr-x  1 mastodon mastodon  32K Feb  8 05:33 node_modules
-rwxr-xr-x  1 mastodon mastodon 6.1K Feb  8 05:23 package.json
-rwxr-xr-x  1 mastodon mastodon  162 Feb  8 05:23 postcss.config.js
-rwxr-xr-x  1 mastodon mastodon   81 Feb  8 05:23 priv-config
drwxr-xr-x  1 mastodon mastodon   33 Feb  8 05:34 public
-rwxr-xr-x  1 mastodon mastodon 3.0K Feb  8 05:23 scalingo.json
drwxr-xr-x 20 mastodon mastodon 4.0K Feb  8 05:23 spec
drwxr-xr-x  2 mastodon mastodon   22 Feb  8 05:23 streaming
-rwxr-xr-x  1 mastodon mastodon  682 Feb  8 05:23 template_engine.py
drwxr-xr-x  1 mastodon mastodon   65 Feb  8 15:17 tmp
drwxr-xr-x  1 mastodon mastodon   20 Feb  8 05:28 vendor
-rwxr-xr-x  1 mastodon mastodon 493K Feb  8 05:23 yarn.lock
```

![image](https://user-images.githubusercontent.com/80433392/153019811-ebd021c7-4275-480d-a6d5-4acc63be0fb9.png)

I see some type of queue system being used in the logs:

```
X-Accel-Mapping header missing
[a70750fa-ad50-47c4-ade6-fde1a1cee266] [ActiveJob] Enqueued ActionMailer::MailDeliveryJob (Job ID: b02973c2-79e3-45c9-bf1f-1549866ef785) to Sidekiq(default) with arguments: "UserMailer", "confirmation_instructions", "deliver_now", {:args=>[#<GlobalID:0x00007f367e9e07d0 @uri=#<URI::GID gid://mastodon/User/2>>, "QHsjXx5HHsANgXQz9aV9"]}
[a70750fa-ad50-47c4-ade6-fde1a1cee266] method=POST path=/auth/confirmation format=html controller=Auth::ConfirmationsController action=create status=302 duration=29.33 view=0.00 db=2.39 location=https://mastodon.idevops.io/auth/setup
```

What are some steps to diagnose this issue? 
Is there a way to view the sending error of the queued request and determine why its not showing up in mailgun as at least trying to send?

Thanks for the help...

**Comment by ClearlyClaire** [comment]
Jobs are handled by sidekiq, so any error log would be in `mastodon-sidekiq`'s logs. I don't know how Kubernetes works, but on a manual installation, you'd check them by doing `journalctl -u mastodon-sidekiq`

**Comment by gzukel** [comment]
Thanks for the tip on how to check I will check here shortly @ClearlyClaire 

@Gargron  on AWS everything is open for outbound traffic right now so that shouldn't be the case. Let me check the sidekiq logs real quick..

**Comment by gzukel** [comment]
@ClearlyClaire mastodon@mastodon-85ff786f88-hxqvp:~$ journalctl -u mastodon-sidekiq
bash: journalctl: command not found

journalctl isn't enabled in the docker file for mastodon. :(

**Comment by Gargron** [comment]
If you're using Docker you don't need journalctl. Just use `docker logs mastodon_sidekiq_1` etc.

**Comment by gzukel** [comment]
I'm running in K8S which runs the docker file in the root of the repo. I assume you're referring to using docker compose @Gargron  and that is a side container that runs?

**Comment by Gargron** [comment]
Yeah, the container name is probably different for you, but logging is part of Docker's core functionality (not docker compose). All Mastodon processes log to stdout.

**Comment by gzukel** [comment]
interesting I'll have to see if that is running as part of the docker file because im not running it explicitly as a side car. If not I will look at docker compose and include it as a sidecar container in my deployment.. I'll update here in a bit.

**Comment by Gargron** [comment]
If you are not running a Sidekiq process it would explain why no e-mails would be sent. Similarly, you need a streaming API process if you want to get real-time notifications in the web app. Check the docker compose configuration for an example of what is needed.

**Comment by gzukel** [comment]
@Gargron  thanks I'll publish my stuff publically for everyone or do a pr so everyone can leverage it who wants to run k8s. However, there needs to be some way to do the auto setup first because we had to redirect pod to /dev/null and run the setup commands to create tables etc and then start the pod while starting process. :) might be worth considereing but thanks I'll have a look.

**Comment by gzukel** [comment]
@Gargron  Thank you I was able to make it work by using some sidecars. 

The only problem I'm having now is:

When I try to save any settings as admin or as user for profile I get:

`An unhandled lowlevel error occurred. The application logs may have details.`

But nothing comes up in the logs to actually say what the error is.

Also I noticed that when you re-share someones content it just mentions them and not the content you we're trying to re-share.

Did I mess something up ?

**Comment by gzukel** [comment]
And because I said I would share..

```

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: -=app_name=-
  namespace: -=kubernetes_namespace=-
  labels:
    app: -=app_name=-
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: -=app_name=-
  template:
    metadata:
      labels:
        app: -=app_name=-
    spec:
      imagePullSecrets:
        - name: -=docker_pull_secret=-
      containers:
        - name: -=app_name=-
          image: -=docker_org_name=-/-=image=-:-=image_tag=-
          volumeMounts:
          - name: -=app_name=-
            mountPath: "/tmp/"
            readOnly: true
          livenessProbe:
            tcpSocket:
              port: -=port=-
            initialDelaySeconds: 60
            periodSeconds: 30
          command: ["/bin/bash"]
          args: ["-c", "cp /tmp/.env.production /opt/mastodon/.env.production && echo 'catfile' && cat /opt/mastodon/.env.production && bundle exec rails s -p -=port=-"]
          ports:
          - name: portone
            containerPort: -=port=-
          - name: porttwo
            containerPort: -=port_two=-
        - name: sidekiq
          image: tootsuite/mastodon:latest
          volumeMounts:
          - name: -=app_name=-
            mountPath: "/tmp/"
            readOnly: true
          command: ["/bin/bash"]
          args: ["-c", "cp /tmp/.env.production /opt/mastodon/.env.production && echo 'catfile' && cat /opt/mastodon/.env.production && bundle exec sidekiq"]
        - name: streaming
          image: tootsuite/mastodon:latest
          volumeMounts:
          - name: -=app_name=-
            mountPath: "/tmp/"
            readOnly: true
          command: ["/bin/bash"]
          args: ["-c", "cp /tmp/.env.production /opt/mastodon/.env.production && echo 'catfile' && cat /opt/mastodon/.env.production && node ./streaming"]
          ports:
          - name: portone
            containerPort: 4000
      volumes:
      - name: -=app_name=-
        secret:
          secretName: -=app_name=-

---
apiVersion: v1
kind: Secret
metadata:
  name: -=app_name=-
  namespace: -=kubernetes_namespace=-
stringData:
  .env.production: |
    LOCAL_DOMAIN=mastodon.domain.com
    SINGLE_USER_MODE=false
    SECRET_KEY_BASE=-=SECRET_KEY_BASE=-
    OTP_SECRET=-=OTP_SECRET=-
    VAPID_PRIVATE_KEY=-=VAPID_PRIVATE_KEY=-
    VAPID_PUBLIC_KEY=-=VAPID_PUBLIC_KEY=-
    DB_HOST=-=DB_HOST=-
    DB_PORT=-=DB_PORT=-
    DB_NAME=-=DB_NAME=-
    DB_USER=-=DB_USER=-
    DB_PASS=-=DB_PASS=-
    REDIS_HOST=-=REDIS_HOST=-
    REDIS_PORT=-=REDIS_PORT=-
    S3_ENABLED=true
    S3_PROTOCOL=https
    S3_BUCKET=mastodon-idevops
    S3_REGION=us-east-1
    S3_HOSTNAME=s3-us-east-1.amazonaws.com
    AWS_ACCESS_KEY_ID=-=AWS_ACCESS_KEY_ID=-
    AWS_SECRET_ACCESS_KEY=-=AWS_SECRET_ACCESS_KEY=-
    SMTP_SERVER=-=SMTP_SERVER=-
    SMTP_PORT=-=SMTP_PORT=-
    SMTP_LOGIN=-=SMTP_LOGIN=-
    SMTP_PASSWORD=-=SMTP_PASSWORD=-
    SMTP_AUTH_METHOD=plain
    SMTP_FROM_ADDRESS=-=SMTP_FROM_ADDRESS=-

---
apiVersion: v1
kind: Service
metadata:
  name: -=app_name=-
  namespace: -=kubernetes_namespace=-
spec:
  type: LoadBalancer
  selector:
    app: -=app_name=-
  ports:
    - name: portone
      port: -=port=-
      targetPort: -=port=-
    - name: porttwo
      port: -=port_two=-
      targetPort: -=port_two=-


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/tls-acme: "true"
  name: mastodon
  namespace: mastodon
spec:
  ingressClassName: nginx
  rules:
  - host: mastodon.domain.com
    http:
      paths:
      - backend:
          service:
            name: mastodon
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - mastodon.domain.com
    secretName: mastodon-tls

```
