### ISSUE TITLE
500 - can't find other users from foreign Mastodon-instances

### ISSUE THREAD

**Issue by jockel127** [mastodon/mastodon#17525]
### Steps to reproduce the problem

My steps:
1. git clone
2. git fetch && git checkout 3.4.6
3. edit docker-compose + envfile 
4. docker-compose build
5. DB Migrate
6. Assets compile

As I wrote in the header I got a '500 internal server' error, when I try to search for another user from a foreign Mastodon-instance. Mastodon is running on docker-containers. 
The logfiles, when I try to search for a user:
```
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] OpenSSL::PKey::RSAError (Neither PUB key nor PRIV key: header too long):
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0]   
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/models/account.rb:273:in `initialize'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/models/account.rb:273:in `new'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/models/account.rb:273:in `keypair'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/lib/request.rb:47:in `on_behalf_of'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/helpers/jsonld_helper.rb:197:in `block in build_request'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/helpers/jsonld_helper.rb:196:in `tap'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/helpers/jsonld_helper.rb:196:in `build_request'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/helpers/jsonld_helper.rb:162:in `fetch_resource_without_id_validation'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/helpers/jsonld_helper.rb:155:in `fetch_resource'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/services/activitypub/fetch_remote_account_service.rb:17:in `call'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/services/resolve_account_service.rb:112:in `block in fetch_account!'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/services/resolve_account_service.rb:110:in `fetch_account!'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/services/resolve_account_service.rb:52:in `call'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/services/account_search_service.rb:32:in `exact_match'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/services/account_search_service.rb:22:in `search_service_results'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/services/account_search_service.rb:14:in `call'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/services/search_service.rb:28:in `perform_accounts_search!'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/services/search_service.rb:18:in `block in call'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/services/search_service.rb:12:in `tap'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/services/search_service.rb:12:in `call'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/controllers/api/v2/search_controller.rb:19:in `search_results'
web_1        | [2be05cc8-b50a-47e0-a167-d88abc9349c0] app/controllers/api/v2/search_controller.rb:12:in `index'
```

My Compose-file:
```
version: '3.5'
services:

  db:
    restart: always
    image: postgres:9.6-alpine
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mastodon", "-d", "mastodon_production"]
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file: .env.production

  redis:
    restart: always
    image: redis:6.0-alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./redis:/data

        #  es:
        #    restart: always
        #    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
        #    environment:
        #      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        #      - "cluster.name=es-mastodon"
        #      - "discovery.type=single-node"
        #      - "bootstrap.memory_lock=true"
        #    networks:
        #      - internal_network
        #    healthcheck:
        #      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
        #    volumes:
        #      - ./elasticsearch:/usr/share/elasticsearch/data
        #    ulimits:
        #      memlock:
        #        soft: -1
        #        hard: -1

  web:
    build: .
    image: tootsuite/mastodon:v3.4.6
    restart: always
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - traefik_proxy
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
      - redis
        #      - es
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.services.mydomain-mastodon-web.loadbalancer.server.port=3000"
      - "traefik.http.routers.mydomain-mastodon-web.rule=Host(`social.mydomain.it`)"
      - "traefik.http.routers.mydomain-mastodon-web.entrypoints=websecure"
      - "traefik.http.routers.mydomain-mastodon-web.tls.certresolver=myresolver"
    volumes:
      - ./public/system:/mastodon/public/system

  streaming:
    build: .
    image: tootsuite/mastodon:v3.4.6
    restart: always
    env_file: .env.production
    command: node ./streaming
    networks:
      - traefik_proxy
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1"]
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db
      - redis
    labels:
      - "traefik.docker.network=traefik_proxy"
      - "traefik.enable=true"
      - "traefik.http.services.mydomain-mastodon-streaming.loadbalancer.server.port=4000"
      - "traefik.http.routers.mydomain-mastodon-streaming.rule=(Host(`social.mydomain.it`) && PathPrefix(`/api/v1/streaming`))"
      - "traefik.http.routers.mydomain-mastodon-streaming.entrypoints=websecure"
      - "traefik.http.routers.mydomain-mastodon-streaming.tls.certresolver=myresolver"

  sidekiq:
    build: .
    image: tootsuite/mastodon:v3.4.6
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system
## Uncomment to enable federation with tor instances along with adding the following ENV variables
## http_proxy=http://privoxy:8118
## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
#  tor:
#    image: sirboops/tor
#    networks:
#      - external_network
#      - internal_network
#
#  privoxy:
#    image: sirboops/privoxy
#    volumes:
#      - ./priv-config:/opt/config
#    networks:
#      - external_network
#      - internal_network

networks:
  traefik_proxy:
      external: true
  external_network:
  internal_network:
      internal: true
```

### Expected behaviour

Search for another users from foreign mastodon-instances

### Actual behaviour

500 internal server error

### Specifications

I tried to use it with Firefox and Chrom*
