### ISSUE TITLE
Mastodon 3.5.0 broken in docker

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [mastodon/mastodon#17927]
### Steps to reproduce the problem

I updated mastodon to 3.5.0 and now I get 500 status code all of the the place,
```
web_1        | [9e74db62-1d38-4fd2-896a-6cc6c229a759] method=GET path=/@esmail format=*/* controller=AccountsController action=show status=500 error='ActionView::Template::Error: undefined local variable or method `edited_at' for #<Status id: 107938967704389259, uri: "https://social.esmailelbob.xyz/users/esmail/status...", text: "Let's hope next month April be good month for me,\n...", created_at: "2022-03-11 16:58:59.833400000 +0000", updated_at: "2022-03-11 16:58:59.833400000 +0000", in_reply_to_id: nil, reblog_of_id: nil, url: nil, sensitive: false, visibility: "public", spoiler_text: "", reply: false, language: "en", conversation_id: 1289, local: true, account_id: 107689060346451808, application_id: 1, in_reply_to_account_id: nil, poll_id: nil, deleted_at: nil>
```
my docker-compose file:
```
version: '3'
services:

  db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - ./postgres14:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    restart: always
    image: redis:6-alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./redis:/data

#  es:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "cluster.name=es-mastodon"
#      - "discovery.type=single-node"
#      - "bootstrap.memory_lock=true"
#    networks:
#      - internal_network
#    healthcheck:
#      test: ["CMD-SHELL", "curl --silent --fail 127.0.0.1:9200/_cluster/health || exit 1"]
#    volumes:
#      - ./elasticsearch:/usr/share/elasticsearch/data
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1

  web:
#    build: .
    image: tootsuite/mastodon:latest
    restart: always
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off 127.0.0.1:3000/health || exit 1"]
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
      - redis
#      - es
    volumes:
      - ./MASTODON_DATA:/mastodon/public/system
      - ./MASTODON_DATA:/mastodon/public/assets
      - ./Mastomoji.tar.gz:/opt/mastodon/Mastomoji.tar.gz
  streaming:
#    build: .
    image: tootsuite/mastodon:latest
    restart: always
    env_file: .env.production
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off 127.0.0.1:4000/api/v1/streaming/health || exit 1"]
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
#    build: .
    image: tootsuite/mastodon:latest
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./MASTODON_DATA:/mastodon/public/system
## Uncomment to enable federation with tor instances along with adding the following ENV variables
## http_proxy=http://privoxy:8118
## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
#  tor:
#    image: sirboops/tor
#    networks:
#      - external_network
#      - internal_network

#  privoxy:
#    image: sirboops/privoxy
#    volumes:
#      - ./priv-config:/opt/config
#    networks:
#      - external_network
#      - internal_network

networks:
  external_network:
  internal_network:
    internal: true
```

### Expected behaviour

3.5.0 ver works fine

### Actual behaviour

blank web page - https://social.esmailelbob.xyz/@esmail

### Specifications

Firefox on linux
