### ISSUE TITLE
custom.css rendered incorrectly

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#18823]
### Steps to reproduce the problem

1. Set custom css like this
```css
a[href="https://qdon.space"] {
  some_css;
}
```
Check `/custom.css`

### Expected behaviour

custom.css are presented as input

### Actual behaviour

single/double quote is escaped for html
```css
.status a[href^=&quot;https://qdon.space/&quot;] .display-name .display-name__html, .detailed-status a[href^=&#39;https://qdon.space/&#39;] .display-name .display-name__html { color: #ffc0fb; }

.status a[href^=&#39;https://beta.qdon.space/&#39;] .display-name .display-name__html, .detailed-status a[href^=&#39;https://beta.qdon.space/&#39;] .display-name .display-name__html { color: #ffc0fb; }
```

### Specifications

commit: c3f0621a59a74d0e20e6db6170894871c48e8f0f
