### ISSUE TITLE
Helm Chart Local PostgreSQL broken by PR #19502

### ISSUE THREAD

**Issue by hardillb** [mastodon/mastodon#19536]
### Steps to reproduce the problem

1. Create a `local.yml` with the minium set of required details e.g.
    ```
    mastodon:
      createAdmin:
        enabled: true
        username: admin
        email: admin@example
      local_domain: example.com
      web_domain: mastodon.example.com
      persistence:
        assets:
          accessMode: ReadWriteMany
          resources:
            requests:
              storage: 10Gi
        system:
          accessMode: ReadWriteMany
          resources:
            requests:
              storage: 10Gi
      smtp:
        auth_method: plain
        delivery_method: smtp
        enable_starttyls_auto: trye
        port: 587
        server: mail.example
        login: admin
        password: password
        from_address: matodon@example.com
      secrets:
        secret_key_base: xxxxxxxxxxxxx
        otp_secret:  xxxxxxxxxxxxx
        vapid:
          private_key:xxxxxxxxxxx
          public_key: xxxxxxxxxxxxxx
    elasticsearch:
      enabled: false
    ingress:
      annotations:
      tls:
      hosts:
      - host: mastodon.example.com
        paths:
        - path: '/'
    postgresql:
      auth:
         password: TopSecret
      primary:
        nodeSelector:
          beta.kubernetes.io/arch: amd64
    redis:
      password: TopSecret
    ```
3. Run `helm upgrade --install --namespace mastodon --create-namesapce mastodon ./chart -f local.yml`
4. Deployment fails to start as it can't find the `postgresql-password` in the generated secrets
...

### Expected behaviour

Helm deployment to work

### Actual behaviour

Multiple pods fail to start due to missing secrets

### Detailed description

I believe the changes in #19502 should be reverted (and redone to use `password` and set `password` to any value passed in for an external database)

The PostgreSQL chart generates the following secret:

```
# Source: mastodon/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mastodon-postgresql
  namespace: mastodon
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-11.1.3
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "xxxxxxx"
  password: "xxxxxxx"
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
```
The bitnami docs:
https://github.com/bitnami/charts/tree/main/bitnami/postgresql#global-parameters

say:

`postgres-password` is admin password
`password` is the user password

### Specifications

What ever is in the "latest" tag on docker hub for the runtime.

Current HEAD of main (https://github.com/mastodon/mastodon/commit/30ef11022487364256656efee3cee92db2c839b2)
