### ISSUE TITLE
Helm chart Deployments have identical labels

### ISSUE THREAD

**Issue by deepy** [mastodon/mastodon#19703]
### Steps to reproduce the problem

Run helm template or inspect a running system to see that:

```yaml
# Source: mastodon/templates/deployment-streaming.yaml
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mastodon
        app.kubernetes.io/instance: mastodon
```

```yaml
# Source: mastodon/templates/deployment-web.yaml
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mastodon
        app.kubernetes.io/instance: mastodon
        component: rails
```

```yaml
# Source: mastodon/templates/deployment-sidekiq.yaml
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mastodon
        app.kubernetes.io/instance: mastodon
        component: rails
```

This combined with the service selectors:
```yaml
# Source: mastodon/templates/service-web.yaml
spec:
  selector:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/instance: mastodon
```

```yaml
# Source: mastodon/templates/service-streaming.yaml
spec:
  selector:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/instance: mastodon
```

### Expected behaviour

pods from different systems have different labels

### Actual behaviour

nginx ingress breaks as service selector matches web, streaming, and sidekiq

### Detailed description

Since each service matches all the pods (web, streaming, and sidekiq) when using nginx ingress most of the requests fails as they're sent to the wrong service.
Traefik on the other hand seems to handle this well, but as nginx is one of the more popular ingresses this should be fixed.
This also breaks additional tooling like: `kubectl logs deployment/mastodon-sidekiq`:

```
$ kubectl logs deployment/mastodon-sidekiq --tail=2
Found 2 pods, using pod/mastodon-web-68c98d496f-nwwgk
[d3dabf98-1de7-4859-a35b-11731a91c949] method=GET path=/health format=*/* controller=HealthController action=show status=200 duration=0.26 view=0.13
[988c137e-bf4b-4e1a-a71f-95343a5a3b79] method=GET path=/health format=*/* controller=HealthController action=show status=200 duration=0.26 view=0.1
```

Unfortunately the selector is immutable, so changing this means breaking upgrades.
Kubernetes documentation has a set of [common labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) in use and my suggestion is that each deployments gets a `app.kubernetes.io/component` matching their component.
That is: web, streaming, and sidekiq
And `app.kubernetes.io/part-of: rails` for the `podAffinity`

### Specifications

latest chart
