### ISSUE TITLE
4.0.0rc2: CW "show more" button stays dark in light theme after being clicked

### ISSUE THREAD

**Issue by abochmann** [mastodon/mastodon#19930]
### Steps to reproduce the problem

1. select light theme
2. find a post with a CW
3. click on "show more"
4. the button now is "show less", but has a dark grey background
5. background temporarily changes to light grey when hovering over the button
6. clicking again to close the CW does not change the button background

### Expected behaviour

CW expansion button keeps its background colour after being selected

### Actual behaviour

it gets stuck on a dark background

### Detailed description

See reproduction.

Screenshot after selecting button:
![image](https://user-images.githubusercontent.com/9380844/200201463-6626577e-e5e7-4b79-8316-8de23f7df7d6.png)

Colour scheme on untouched button:
![image](https://user-images.githubusercontent.com/9380844/200201500-d988ece9-b620-4a63-b894-44f51951f2c3.png)

### Specifications

Mastodon 4.0.0rc2

**Comment by zachflanders** [comment]
I was able to reproduce with Firefox 106.0.5 (64-bit) and Chrome Version 107.0.5304.87 on MacOS 12.3.1.  The bug didn't show up in Safari 15.4.  Interesting when you inspect in dev tools on chrome or firefox it shows the correct computed value.  In Firefox if you use the color grabber tool, the tooltip shows the correct color, even while the rendered button is the wrong color (see screenshot.)
<img width="215" alt="Screen Shot 2022-11-06 at 11 24 48 PM" src="https://user-images.githubusercontent.com/2885925/200232774-5648d7d0-550b-49b2-a844-aa6f71b0c89a.png">
The css selectors are duplicated in the diff.scss file which gets imported after the component.scss file, so it should take precedence, but it appears that they are not in Chrome and Firefox.

**Comment by zachflanders** [comment]
Adding `!important` in the diff.scss seems to fix the issue:
```scss
// Change the background colors of status__content__spoiler-link
.reply-indicator__content .status__content__spoiler-link,
.status__content .status__content__spoiler-link {
  background: $ui-base-color !important; 

  &:hover {
    background: lighten($ui-base-color, 4%) !important;
  }
}
```
