### ISSUE TITLE
Bigger more detailed link previews, and showing link previews when writing a post

### ISSUE THREAD

**Issue by innosflew** [mastodon/mastodon#19984]
### Pitch

Showing link previews when you are writing a post. Here is my poor mockup for it:
![](https://i.imgur.com/9Suhub8.png)
Also, allow people to optionally remove link previews during editing if they don't want their posts to have an link preview for whatever reason.

-----------------------------------------
Also, a little bigger link previews on both the timeline and in posts, and also include a description for the link previewss on the timeline.

This is how the link previews look on the timeline right now:
![](https://i.imgur.com/wYGwoLI.png)

And this is my proposal how they should look:
![](https://i.imgur.com/GKPKB1Q.png)

-----------------------------------------
This is how the link previews look within posts right now:
![](https://i.imgur.com/SBtjid5.png)

And this is my proposal how they should look:
![](https://i.imgur.com/ZaGqeR7.png)

### Motivation

Having link previews during editing would really help people because they would know how would their posts would look like with a link preview. Also, the ability to optionally remove all link previews from your post during editing would also be useful for those who don't want to have them in their post for whatever reason. These are features that most other social media sites already have.

Also, I think having bigger and more detailed link previews on the timeline and in posts would look much better and would add to the user experience in my personal opinion.

**Comment by afontenot** [comment]
I would edit the title of this issue from "embeds" to "link previews". Mastodon has a different feature called embeds, so as written it's a little misleading.

**Comment by innosflew** [comment]
> I would edit the title of this issue from "embeds" to "link previews". Mastodon has a different feature called embeds, so as written it's a little misleading.

Thank you I updated my post

**Comment by pkreissel** [comment]
Hi there, small media startup member here: It would be extremely great, if the image for the link preview would be much bigger. This is the case on all major networks like Facebook and Twitter, because more people click on links if you can already show them interesting content in the preview image. To make Mastodon an interesting platform for news websites and journalists this would be very much appreciated by everyone I think.

**Comment by innosflew** [comment]
Inspired by you I've also decided to modify link previews in my instance myself.

I've added this to my CSS:
```css
a.status-card,
a.status-card.compact {
    background-color: #191b22;
    display: block;
    border-radius: 10px;
}

.fa-file-text::before {
    content: "";
}

a.status-card .status-card__image-image,
a.status-card .status-card__image-image.compact {
    border-radius: 0px;
}

a.status-card .status-card__content,
a.status-card.compact .status-card__content {
    padding: 15px;
}

a.status-card .status-card__title,
a.status-card.compact .status-card__title {
    font-size: 18px;
    margin-bottom: 10px;
    font-weight: normal;
    color: white;
    white-space: inherit;
}

a.status-card .status-card__host,
a.status-card.compact .status-card__host {
    font-size: 14px;
    color: #71767b;
    margin-top: 0px;
    margin-bottom: 5px;
}

a.status-card .status-card__description,
a.status-card.compact .status-card__description {
    color: #71767b;
}
```
Then I went and edited the following file: `/home/mastodon/live/app/javascript/mastodon/features/status/components/card.js`

In there I replaced the 202 line:
```Javascript
    const description = (
      <div className='status-card__content'>
        {title}
        {!(horizontal || compact) && <p className='status-card__description'>{trim(card.get('description') || '', maxDescription)}</p>}
        <span className='status-card__host'>{provider}</span>
      </div>
    );
```
With this:
```Javascript
    const description = (
      <div className='status-card__content'>
        <span className='status-card__host'>{provider}</span>
        {title}
        {!horizontal && <p className='status-card__description'>{trim(card.get('description') || '', 300)}</p>}
      </div>
    );
```
I did this in order to move the provider line from the bottom to the top above the tittle. It also enables the description everywhere, and increases the character count of the description from 50 to 300.

After this I recompiled my assets and restarted the mastodon processes, and now my embeds look like this:
![](https://i.imgur.com/lht1rTE.png)
![](https://i.imgur.com/FxBA1EV.png)

They even scale well on mobile:
![](https://i.imgur.com/rAIWyzH.jpeg)

The only thing I couldn't figure out yet is how increase the resolution of the thumbnails a little bit, because they can look a little bit blurry.

**Comment by kmhcreative** [comment]
When I posted before I didn't know the Mastodon webapp is theme-able.  Actually it was a post in my Fediverse feed that clued me in.  And if your instance admin doesn't include a theme option you can just apply it _yourself_ with the "[Stylus](https://github.com/openstyles/stylus)" extension for Chromium and Mozilla-based browsers.  

Many user themes for Mastodon already available and you can create your own custom themes if you want for yourself or to share.  I'm using the extension to modify Mastodon in Google Chrome, since it doesn't support user stylesheets anymore.  Someone did create a beta version of "Stylus" for Safari now that it supports WebExtensions, but it has issues and you have to enable unsigned extensions. You're better off using a custom stylesheet in Safari.  I'm using a custom _userContent.css_ file in Firefox that was easily adapted for Safari.

For Firefox _userContent.css_ and the "Stylus" extension:

```css
/* MASTODON BIG PREVIEWS */
@-moz-document domain('mastodon.social') { /* or whichever instance you are on */
	.status-card.compact {
		border-color: #313543 !important;
		background-color: #17191f !important;
		display: block !important;
		border-radius: 4px !important;
	}
		.status-card.compact:hover {
			background-color: #313543 !important;
		}

	.status-card.compact .status-card__image {
		border-radius: 4px 4px 0px 0px !important;
		overflow: hidden !important;
		max-height: 400px !important;
	}

	.status-card.compact .status-card__title { 
			/* same as Explore News headlines */
		font-size: 19px !important;
		line-height: 24px !important;
		font-weight: 500 !important;
		margin-bottom: 4px !important;
		overflow: visible !important;
		white-space: normal !important;
	}

	.status-card__host {
		display: block !important;
		margin-top: 5px !important;
		font-size: 16px !important; /* bumped up font from 13px */
		overflow: hidden !important;
		text-overflow: ellipsis !important;
		white-space: nowrap !important;
	}
		body.theme-mastodon-light .status-card.compact {
			border-color: #c9cdd9 !important;
			background-color: #eff3f5 !important;
		}
			body.theme-mastodon-light .status-card.compact:hover {
				background-color: #c0cdd9 !important;
			}
}
```

Safari doesn't understand _@-moz-document_ or _@-document_ so you need to use some other way to target Mastodon.  There appears to be high level DIV container with the _id="mastodon"_ so I used that.  This would also work for Firefox and Stylus too, and Firefox and Safari could share the same user stylesheet if you wanted.  This _should_ also apply to **any** Mastodon instance you visit:

```css
/* MASTODON BIG PREVIEWS */

	#mastodon .status-card.compact {
		border-color: #313543 !important;
		background-color: #17191f !important;
		display: block !important;
		border-radius: 4px !important;
	}
		#mastodon .status-card.compact:hover {
			background-color: #313543 !important;
		}

	#mastodon .status-card.compact #mastodon .status-card__image {
		border-radius: 4px 4px 0px 0px !important;
		overflow: hidden !important;
		max-height: 400px !important;
	}

	#mastodon .status-card.compact #mastodon .status-card__title { 
			/* same as Explore News headlines */
		font-size: 19px !important;
		line-height: 24px !important;
		font-weight: 500 !important;
		margin-bottom: 4px !important;
		overflow: visible !important;
		white-space: normal !important;
	}

	#mastodon .status-card__host {
		display: block !important;
		margin-top: 5px !important;
		font-size: 16px !important; /* bumped up font from 13px */
		overflow: hidden !important;
		text-overflow: ellipsis !important;
		white-space: nowrap !important;
	}
		body.theme-mastodon-light #mastodon .status-card.compact {
			border-color: #c9cdd9 !important;
			background-color: #eff3f5 !important;
		}
			body.theme-mastodon-light #mastodon .status-card.compact:hover {
				background-color: #c0cdd9 !important;
			}
```

As for the larger images sometimes being blurry that's totally dependent on what size the preview images are on the server that's being linked to.  Some websites might serve up full size images that look great, others might be sending tiny thumbnails that when blown up are a pixelated mess.  On our end, as users, we have no control over the size or resolution of source images being pulled.  We get what we get.

Theming Mastodon is probably a better approach anyway.  There's no way to make the UI perfect for everyone, but it would make sense to make it easier for people to apply themes to it - or at least make them more aware it CAN be themed - because not everyone using Mastodon has the technical skills to code UI modifications.  The "Stylus" extension is easy enough though, I think most people can figure it out.  But it obviously isn't an option for people using the apps.
