### ISSUE TITLE
Helm chart cannot be updated, dependencies are too old

### ISSUE THREAD

**Issue by metal3d** [mastodon/mastodon#20547]
### Steps to reproduce the problem

1. Get mastodon repo, use whatever the tag you want (stable-3.4, release-3.5.3...)
2. Go to `chart`
3. Type `help dep update`

### Expected behaviour

The dependencies should be downloaded

### Actual behaviour

An error occured

### Detailed description

```
$ helm dep update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: can't get a valid version for repositories elasticsearch, postgresql, redis. Try changing the version constraint in Chart.yaml
```

### Specifications

Whatever the version of Mastodon :)

Actually, none of the versions are actually OK, Going to artifacthub.io to check, the listed versions in the Chart.yaml file are now very old and not listed.

**Comment by bocan** [comment]
I can't duplicate that.

```
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami" chart repository
...Successfully got an update from the "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami" chart repository
...Successfully got an update from the "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami" chart repository
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
Downloading elasticsearch from repo https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
Downloading postgresql from repo https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
Downloading redis from repo https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
Deleting outdated charts
```

**Comment by metal3d** [comment]
Wow... what the hell...
The Chart.yaml now points on archives from github (in the main branch) and it's OK for this branch.

But... I want to update my Mastodon instance from 3.5.1 to 3.5.3. Using the `v3.5.3` tag, the problem persists because the dependencies are outdated:

```yaml
dependencies:
  - name: elasticsearch
    version: 15.10.3
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  - name: postgresql
    version: 8.10.14
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 10.9.0
    repository: https://charts.bitnami.com/bitnami
```

The problem heppens on release branches so.
