### ISSUE TITLE
3-dot menu not visible for profile on small columns

### ISSUE THREAD

**Issue by pixel-fabian** [mastodon/mastodon#20568]
### Steps to reproduce the problem

1. Activate advanced interface options
2. Add more columns (e.g. for hashtags or lists)
3. Open a profile in feed (e.g. (/web/@nextcloud@mastodon.xyz)
![3-dot_profile](https://user-images.githubusercontent.com/82926714/201525478-ffc9fc3d-cd65-45be-9d54-4e8146726c85.jpg)

### Expected behaviour

The 3-dot menu for profiles is visible

### Actual behaviour

The 3-dot menu is not visible

### Detailed description

The column has a min-width of 300px on big screens:
```css
@media screen and (min-width: 1025px)
.layout-multiple-columns .column, .layout-multiple-columns .drawer {
  flex: 1 1 auto;
  min-width: 300px;
  max-width: 400px;
}
```
There is not enough space within `account__header__tabs__buttons` to display all buttons.

### Specifications

Mastodon v3.5.3
Firefox 106.0.5 (64-Bit)
