### ISSUE TITLE
Helm chart autoscaling doesn't scale the web deployment

### ISSUE THREAD

**Issue by grrywlsn** [mastodon/mastodon#20691]
### Steps to reproduce the problem

1. I set the `autoscaling.enabled` to `true` and set `minReplicas` as described in the values.yaml
2. I deployed the Helm chart, and noticed the pod count was incorrect
3. The HPA throws an error:

```
status:
  conditions:
  - lastTransitionTime: "2022-11-14T20:13:29Z"
    message: 'the HPA controller was unable to get the target''s current scale: deployments/scale.apps
      "mastodon" not found'
```

4. Checking the names, the name for the target of the HPA and the rendered name of the deployment do not match.

### Expected behaviour

The HPA should set the number of pods in the deployment correctly

### Actual behaviour

The pod stayed at one and the HPA could not find the deployment to scale it

### Specifications

Latest version of the chart.
