### ISSUE TITLE
Possibility to change the text of the "Publish!" button

### ISSUE THREAD

**Issue by wioxjk** [mastodon/mastodon#20751]
### Pitch

Before 4.0, the button had the text "Toot!" - which made Mastodon unique, less corporate and boring and more fun/interesting.
It would be nice if we easily could change the text of the button in the UI, because currently it requires us to enter the code and change it manually - which makes docker and k8s deployment not fun to take care of.

### Motivation

The motivation is to keep Mastodon - Mastodon, and not Lotus Notes.

**Comment by jiangshanghan** [comment]
agree. as a coordinator,I prefer the "change" function especially if it can be put in the Admin Backend... I'm sure our users will feel interesting about that!

**Comment by Cassolotl** [comment]
If it was me I'd just make it a pen icon, because it's smaller. :D

**Comment by ineffyble** [comment]
I'm attempting to write the code for this but it's been ages since I worked in the codebase.

**Comment by ineffyble** [comment]
Quick CSS snippet you can add to Custom CSS (under Site Settings -> Appearance) to restore back to "Toot!":

```
.compose-form__publish-button-wrapper button {
  color: rgba(255,255,255,0);
}

.compose-form__publish-button-wrapper button::before {
  content: "Toot!";
  position: absolute;
  top: 50%;
  left: 50%;
  color: rgba(255,255,255,1);
  transform: translate3d(-50%, -50%, 0);
}
```

Inspired by @me@andr3.net.

**Comment by Qsionc** [comment]
Ekhm...


Where `toot`?

**Comment by goldjg** [comment]
This needs to be configurable in a per user basis. There is more chance of me being travelling to another planet in my lifetime than every user on an instance managing to agree what they want that button to say!

**Comment by ineffyble** [comment]
@goldjg I think if individual users care that much they should use a browser extension to be honest.

**Comment by goldjg** [comment]
That’s problematic - lots of malicious extensions out there. Not everyone is savvy enough and has the knowledge to be able to vet which extensions are safe and which aren’t.

Regards,
Graham

**Comment by ineffyble** [comment]
If there's power users who want a custom button, my suggestion would just be to use one of the big user script extensions that let you provide custom CSS, and then use a snippet such as the above.

I don't feel customising labels on UI elements _per-user_ is super important in the scheme of things, maybe others feel differently.

**Comment by skyfaller** [comment]
> Quick CSS snippet you can add to Custom CSS (under Site Settings -> Appearance) to restore back to "Toot!":

This only works in desktop view, not mobile view. Here's an augmented version that also covers the button in the mobile view:

```css
.compose-form__publish-button-wrapper button, .ui__header__links .button {
  text-indent: -9999px;
  line-height: 0; /* Collapse the original line */
}

.compose-form__publish-button-wrapper button:after, .ui__header__links .button:after {
  content:'Toot!'; 
  text-indent: 0;
  display: block;
  line-height: initial; /* New content takes up original line height */
}
```
