### ISSUE TITLE
Error 401 on push/pull requests after hardware failure

### ISSUE THREAD

**Issue by Science4583** [mastodon/mastodon#21628]
### Steps to reproduce the problem

1. Deploy Mastodon with Docker behind Traefik
2. Use Mastodon and be happy everything works
3. Remove power for Mastodon hosts unexpectedly
4. Restore power
5. Everything loads without any errors but all push/pull jobs fail with error 401
...

### Expected behaviour

Push/Pull jobs succed 200

### Actual behaviour

Jobs fail with error 401

### Detailed description

I setup Mastodon on my Docker Swarm as a stack: Mastodon Web, Sidekiq, Streaming, Redis, Postgres, Elasticsearch. For days everything was working perfectly, even restarting Swarm hosts didn't cause any issues, the containers just move around.

Power was cut to all the Swarm hosts without warning. Upon restart everything comes up perfectly.

I can login to Mastodon and see everything as it should be but nothing is updating. Sidekiq shows all the push/pull jobs failing with a 401 error.

I've verified the `.well-known/webfinger` works and there's no permission issues being reported or that look out of place. DNS is correct and hasn't changed. I've turned on debugging and only the 401 errors show up as anything useful I can see.

I'm very stumped

### Specifications

Mastodon 4.0.2 (docker tootsuite/mastodon)
Redis 7.0.5
Postgres 14
Elasticsearch 7.17

**Comment by Science4583** [comment]
Sidekiq errors are all the same
```
Mastodon::UnexpectedResponseError: https://mastodon.online/inbox returned code 401
```

This is a sanitized version of the Stack
```yaml
version: "3.7"

services:
  
  server:
    image: tootsuite/mastodon
    restart: unless-stopped
    # Needed for initial database config
    #command: bash -c "while true; do sleep 2; date; done"
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.mastodon.rule: "Host(`domain.com`)"
        traefik.http.routers.mastodon.entrypoints: "https"
        traefik.http.routers.mastodon.tls: "true"
        traefik.http.routers.mastodon.tls.certresolver: dns1
        traefik.http.services.mastodon.loadbalancer.server.port: "3000"
        traefik.http.routers.mastodon.middlewares: "secure-headers"
    environment:
      TZ: "America/Someplace"
      LOCAL_DOMAIN: "domain.com"
      SINGLE_USER_MODE: "false"
      SECRET_KEY_BASE: "changeme"
      OTP_SECRET: "changeme"
      VAPID_PRIVATE_KEY: "changeme"
      VAPID_PUBLIC_KEY: "changeme"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASS: "changeme"
      ES_HOST: "elasticsearc"
      ES_PORT: "9200"
      ES_USER: "elastic"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "changme"
      SMTP_SERVER: "changeme"
      SMTP_PORT: "587"
      SMTP_LOGIN: "username"
      SMTP_PASSWORD: "password"
      SMTP_AUTH_METHOD: "plain"
      SMTP_OPENSSL_VERIFY_MODE: "none"
      SMTP_ENABLE_STARTTLS: "auto"
      SMTP_FROM_ADDRESS: "<address>"
    volumes:
      - mastodon_data:/mastodon/public/system
      - /etc/localtime:/etc/localtime
    networks:
      - traefik_wan
      - mastodon_private

  streaming:
    image: tootsuite/mastodon
    restart: unless-stopped
    command: node ./streaming
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']
    environment:
      TZ: "America/Someplace"
      LOCAL_DOMAIN: "domain.com"
      SINGLE_USER_MODE: "false"
      SECRET_KEY_BASE: "changeme"
      OTP_SECRET: "changeme"
      VAPID_PRIVATE_KEY: "changeme"
      VAPID_PUBLIC_KEY: "changeme"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASS: "changeme"
      ES_HOST: "elasticsearc"
      ES_PORT: "9200"
      ES_USER: "elastic"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "changme"
      SMTP_SERVER: "changeme"
      SMTP_PORT: "587"
      SMTP_LOGIN: "username"
      SMTP_PASSWORD: "password"
      SMTP_AUTH_METHOD: "plain"
      SMTP_OPENSSL_VERIFY_MODE: "none"
      SMTP_ENABLE_STARTTLS: "auto"
      SMTP_FROM_ADDRESS: "<address>"
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.mastodon-api.entrypoints: "https"
        traefik.http.routers.mastodon-api.rule: "(Host(`domain.com`) && PathPrefix(`/api/v1/streaming`))"
        traefik.http.routers.mastodon-api.tls: "true"
        traefik.http.routers.mastodon-api.tls.certresolver: dns1
        traefik.http.services.mastodon-api.loadbalancer.server.port: "4000"
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - traefik_wan
      - mastodon_private

  sidekiq:
    image: tootsuite/mastodon
    restart: unless-stopped
    command: bundle exec sidekiq
    environment:
      TZ: "America/Someplace"
      LOCAL_DOMAIN: "domain.com"
      SINGLE_USER_MODE: "false"
      SECRET_KEY_BASE: "changeme"
      OTP_SECRET: "changeme"
      VAPID_PRIVATE_KEY: "changeme"
      VAPID_PUBLIC_KEY: "changeme"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "postgres"
      DB_USER: "changeme"
      DB_PASS: "changeme"
      ES_HOST: "elasticsearc"
      ES_PORT: "9200"
      ES_USER: "elastic"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "changme"
      SMTP_SERVER: "changeme"
      SMTP_PORT: "587"
      SMTP_LOGIN: "username"
      SMTP_PASSWORD: "password"
      SMTP_AUTH_METHOD: "plain"
      SMTP_OPENSSL_VERIFY_MODE: "none"
      SMTP_ENABLE_STARTTLS: "auto"
      SMTP_FROM_ADDRESS: "<address>"
    networks:
      - mastodon_private
    volumes:
      - mastodon_data:/mastodon/public/system
      - /etc/localtime:/etc/localtime
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]

  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    shm_size: 256mb
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime
    networks:
      - mastodon_private

  elasticsearch:
    image: elasticsearch:7.17.7
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 1g
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime
    environment:
      TAKE_FILE_OWNERSHIP: "true"
      http.host: "0.0.0.0"
      transport.host: "localhost"
      network.host: "0.0.0.0"
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms512m -Xmx1g"
      bootstrap.memory_lock: "true"
    networks:
      - mastodon_private

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --requirepass mastodon
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - redis:/data
      - /etc/localtime:/etc/localtime
    networks:
      - mastodon_private

networks:

  traefik_wan:
    external: true
  
  mastodon_private:

volumes:

  mastodon_data:
    driver_opts:
      type: "nfs"
      o: "addr=storageHost,nolock,soft,rw,vers=4.2"
      device: ":/path/for/docker/mastodon/data"

  redis:
    driver_opts:
      type: "nfs"
      o: "addr=storageHost,nolock,soft,rw,vers=4.2"
      device: ":/path/for/docker/mastodon/redis"

  postgres:
    driver_opts:
      type: "nfs"
      o: "addr=storageHost,nolock,soft,rw,vers=4.2"
      device: ":/path/for/docker/mastodon/postgres"

  elasticsearch:
    driver_opts:
      type: "nfs"
      o: "addr=storageHost,nolock,soft,rw,vers=4.2"
      device: ":/path/for/docker/mastodon/elasticsearch"
```
