### ISSUE TITLE
Default to full-width images in link previews and respect twitter:card settings

### ISSUE THREAD

**Issue by MalwareTech** [mastodon/mastodon#21874]
### Pitch

Most social media platform now use a link preview card with a full width image at the top, then the title/link/description below.

Example card from Facebook:
![facebook_card](https://user-images.githubusercontent.com/7256561/204726544-cc2f1170-9588-49b0-91db-87c3428dea5b.png)

On top of parsing with standard OpenGraph format, Twitter also has its own which allows you to choose between one of two style by setting `<meta name="twitter:card" content="summary">` or `<meta name="twitter:card" content="summary_large_image">`

Which will result in 
![summary_card](https://user-images.githubusercontent.com/7256561/204728034-0998f71c-4ee8-4386-a4c3-bd408220acd4.png)
*summary*

or

![summary_card_large](https://user-images.githubusercontent.com/7256561/204728053-e1cfc7d2-e4e6-4336-89f0-9edb7866c1ad.png)
*summary_large_image*

I think it'd be great if Mastodon defaulted to the full-width image format, or gave users a choice through either link metadata or toot options.

### Motivation

Journalists and bloggers typically design their article thumbnail images for the full-width image format. Since the full width format has an aspect ratio of around 2:1, when cropped down to 1:1 the images often become unsightly or even unreadable. 

The legacy format also leads to significantly lower click-through-rate even when using images with correct aspect ratio. 

I've noticed this has become quite a sticking point, and many publishers are opting to fake the feature by attaching large images to their post which can cause formatting issues with different clients. I believe this will lead to higher resource utilization as instances now have to deal with the attached image, as well as the cached one from any link previews generated.

**Comment by chusopr** [comment]
I don't think that's something I would like to see changed. Or at least not something that I cannot disable if it's changed.

I like how Mastodon web client discreetly shows link previews without taking a lot of space as opposed to Twitter taking a lot of the timeline space for link previews that could be used to show more tweets instead.
I just checked my Twitter timeline now and one single tweet took almost the whole viewable timeline on my 1600x900 screen.

I understand that publishers want to give more relevance to their links, but as a user (who occasionally also publishes some content) I don't want publishers to be able to occupy my whole viewable timeline to give more relevance to their links.

**Comment by renchap** [comment]
This can be a setting, similar to the one currently existing for cropping images:
![image](https://user-images.githubusercontent.com/42070/204874723-7eeff933-4982-473c-9c1d-b3c1f2ad400f.png)

**Comment by innosflew** [comment]
I actually implemented something similar on my instance to make preview cards look like this:
![](https://i.imgur.com/wv2xrgo.png)
![](https://i.imgur.com/n3sGufI.png)
![](https://i.imgur.com/auqchBE.png)

They also scale well on mobile if you are looking at Mastodon from a mobile browser.

You can see more examples on my instance. For example on this account which posts a lot of links: https://mstodon.eu/@eunews

If it helps the way I did this is by adding this to my Custom CSS under Preferences>Administration>Server Settings>Appearance:
```CSS
a.status-card,
a.status-card.compact {
    background-color: #191b22;
    display: block;
    border-radius: 10px;
}

.fa-file-text::before {
    content: "";
}

a.status-card .status-card__image-image,
a.status-card .status-card__image-image.compact {
    border-radius: 0px;
}

a.status-card .status-card__content,
a.status-card.compact .status-card__content {
    padding: 15px;
}

a.status-card .status-card__title,
a.status-card.compact .status-card__title {
    font-size: 18px;
    margin-bottom: 10px;
    font-weight: normal;
    color: white;
    white-space: inherit;
}

a.status-card .status-card__host,
a.status-card.compact .status-card__host {
    font-size: 14px;
    color: #71767b;
    margin-top: 0px;
    margin-bottom: 5px;
}

a.status-card .status-card__description,
a.status-card.compact .status-card__description {
    color: #71767b;
}
```

Then I went and edited the following file: `/home/mastodon/live/app/javascript/mastodon/features/status/components/card.js`

In there I replaced the 202 line:
```Javascript
    const description = (
      <div className='status-card__content'>
        {title}
        {!(horizontal || compact) && <p className='status-card__description'>{trim(card.get('description') || '', maxDescription)}</p>}
        <span className='status-card__host'>{provider}</span>
      </div>
    );
```
With this:
```Javascript
    const description = (
      <div className='status-card__content'>
        <span className='status-card__host'>{provider}</span>
        {title}
        {!horizontal && <p className='status-card__description'>{trim(card.get('description') || '', 300)}</p>}
      </div>
    );
```

Then I replaced the 263 line:
```Javascript
{!compact && description}
```
With this:
```Javascript
{description}
```
I did this in order to move the provider line from the bottom to the top above the tittle. It also enables the description everywhere, and increases the character count of the description from 50 to 300.

Then I went and edited another file: `/home/mastodon/live/app/models/preview_card.rb`

In there I replaced the 123 line:
```
geometry: '400x400>',
```
With this:
```
geometry: '548x548>',
```
This was done to increase the resolution of the thumbnails just a little bit because when you increase their size to fit the whole width of the post they can look a bit blurry.

After this I recompiled my assets and restarted the mastodon processes.
