### ISSUE TITLE
Visual indicator about direct messages

### ISSUE THREAD

**Issue by ronilaukkarinen** [mastodon/mastodon#22158]
### Pitch

Currently the direct messages are part of the feed. Every time I receive one, I mistakenly think they're public messages and realize only after their private nature. There should be some clear UI indicator about this. Right now I have experimented with CSS to find a temporary solution.

![ezgif-5-19c81d24a1](https://user-images.githubusercontent.com/1534150/206466525-1c685c0c-71a7-46b4-a832-7a02a3a555e3.gif)

Here's _a draft work in progress_:

```css
.fa[title="Mentioned people only"]::after {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    content: '';
    display: inline-block;
    background: [#f15f5a](https://mementomori.social/tags/f15f5a);
    order: 1;
    animation: pulse-animation 2s infinite;
}

.fa[title="Mentioned people only"]::before {
    order: 2;
}

.fa[title="Mentioned people only"] {
    color: [#f15f5a](https://mementomori.social/tags/f15f5a);
    display: inline-flex;
    align-items: center;
    gap: 8px;
    transform: translateY(-2px)
}

.status-direct .status__relative-time {
    color: [#f15f5a](https://mementomori.social/tags/f15f5a);
    display: inline-flex;
    align-items: center;
}

.status__visibility-icon {
    display: inline-flex
    align-items: center;    
    padding-top: 0;
    margin-top: 0;
}

@keyframes pulse-animation {
  0% {
    box-shadow: 0 0 0 0px rgba(241, 95, 90, 0.5);
  }
    
  100% {
    box-shadow: 0 0 0 10px rgba(241, 95, 90, 0);
  }
}
```

Related [Mastodon post](https://mementomori.social/@rolle/109478315195937110).

### Motivation

It's not clear for many users to notice DMs. We should improve the UI of this feature.

**Comment by pachevalier** [comment]
I strongly support this issue.

**Comment by mirisuzanne** [comment]
We did something similar on front-end.social, with the following styles to more clearly 'mark' direct messages:

```css
.status__wrapper-direct,
.detailed-status-direct {
  background-image: linear-gradient(
    0.375turn,
    #8c8dff 3.5rem,
    transparent 3rem
  );
}
```

We got the idea from other instances, after a number of complaints and requests - then adjusted a few times to find a styles that was both noticeable and non-invasive. There might be even better options, but this has been working well for us:

![Sample DM with a purple triangle in the top right, behind the avatar](https://user-images.githubusercontent.com/104161/207942003-f3f4c823-7dc4-4cee-be12-5c7d64bb4315.jpg)

The fact that DMs show up with other posts makes sense from a technical perspective, but it also makes people nervous - especially since the privacy settings of a post are somewhat subtle to notice. We had a number of people requesting something more clear, to distinguish DMs specifically, but this could be expanded to more clearly mark other privacy settings as well.
