### ISSUE TITLE
Add styling to indicate direct messages (and other post-privacy settings?) in the feed.

### ISSUE THREAD

**Issue by mirisuzanne** [mastodon/mastodon#22336]
### Pitch

On front-end.social we added the following styles to more clearly 'mark' direct messages:

```css
.status__wrapper-direct,
.detailed-status-direct {
  background-image: linear-gradient(
    0.375turn,
    #8c8dff 3.5rem,
    transparent 3rem
  );
}
```

We got the idea from other instance admins who had done similar - and adjusted a few times to find a styles that was both noticeable and non-invasive. There might be even better options, but this has been working well for us:

![Sample DM with a purple triangle in the top right, behind the avatar](https://user-images.githubusercontent.com/104161/207942003-f3f4c823-7dc4-4cee-be12-5c7d64bb4315.jpg)

### Motivation

The fact that DMs show up with other posts makes sense from a technical perspective, but it also makes people nervous - especially since the privacy settings of a post are somewhat subtle to notice. We had a number of people requesting something more clear, to distinguish DMs specifically, but this could be expanded to more clearly mark other privacy settings as well.
