### ISSUE TITLE
Deprecated warning from sidekiq (docker)

### ISSUE THREAD

**Issue by RPHllc** [mastodon/mastodon#25980]
### Steps to reproduce the problem

1. Setup docker-compose.yml as recommended
2. The sidekiq section picks image from v4.1.4
4. Launch docker compose up | grep WARN
5. Read the onscreen logs
...

### Expected behaviour

The deprecated warning should not show up

### Actual behaviour

Deprecated warning shows up, other issues arise after it.

### Detailed description

This is the relevant section of my docker-compose.yml

```
sidekiq:
    image: tootsuite/mastodon:v4.1.4
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq -c 1
```

This is what shows in the log

2023-07-13T19:47:05.560Z pid=6 tid=76a WARN: config.options[:key] = value is deprecated, use config[:key] = value: ["/opt/mastodon/lib/mastodon/redis_config.rb:38:in <top (required)>'", "/opt/mastodon/config/application.rb:55:in require_relative'"]

I went to sidekick repository, the issue is already resolved. You now need to upgrade the version of sidekick in the mastodon build. The references to the issue there are:
- https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/384
- https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/450

### Specifications

Docker image version 4.1.4
