### ISSUE TITLE
Emoji selector displays poorly when browser is zoomed

### ISSUE THREAD

**Issue by lise-henry** [mastodon/mastodon#26549]
### Steps to reproduce the problem

* Zoom in your browser
* Start composing a toot
* Open the emoji picker

### Expected behaviour

The emoji picker should either be displayed in its entirety, or the page should be scrollable to display the entire emojis

### Actual behaviour

Only part of the emoji picker appears, and it is impossible to scroll the page down to see the rest

### Detailed description

Here's a screenshot of what appears currently 
![Screenshot 2023-08-18 at 23-48-50 Mastodon](https://github.com/mastodon/mastodon/assets/1961791/cab272ad-946b-4889-bec1-2ab2e50f953f)

A workaround (that I used in Stylus) is to disable the "transform" property to one of the div around the emoji picker dropdown menu:

```css
div#mastodon + div.logo-resources + textarea + div {
    transform: none !important;
    width: unset !important;
}

.emoji-picker-dropdown__menu {
    margin: 10vh 0 0 0;
}

.emoji-mart {
    width: 100vw;
    height: 90vh;
    display: flex;
    flex-direction: column;
}

.emoji-mart-scroll {
    flex: 1;
    max-height: unset;
}
```

Obviously it's not the best solution, though.

### Mastodon instance

Any, but mastodon.social does it too

### Mastodon version

v4.2.0+pr-26510-2d7b480 and before

### Browser name and version

Firefox 116, same thing with Chromium 114

### Operating system

Debian GNU/Linux trixie/sid
