### ISSUE TITLE
Mastodon 4.2.0 streaming server is in a crash loop on start

### ISSUE THREAD

**Issue by offbyone** [mastodon/mastodon#27182]
### Steps to reproduce the problem

After updating to Mastodon 4.2.0, attempt to start the streaming server:

```shellsession
$ docker-compose up --no-deps --force-recreate streaming
Recreating mastodon_streaming_1
Attaching to mastodon_streaming_1
streaming_1          | node[6]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
streaming_1          |  1: 0xc9adf0 node::Abort() [node]
streaming_1          |  2: 0xc9ae6e  [node]
streaming_1          |  3: 0xd194b9 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
streaming_1          |  4: 0xd195dc node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
streaming_1          |  5: 0xc548c3  [node]
streaming_1          |  6: 0xc55254 node::Start(int, char**) [node]
streaming_1          |  7: 0x7f3ba52fd1ca  [/lib/x86_64-linux-gnu/libc.so.6]
streaming_1          |  8: 0x7f3ba52fd285 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
streaming_1          |  9: 0xbb0e5e _start [node]
mastodon_streaming_1 exited with code 134
```

### Expected behaviour

streaming should be up

### Actual behaviour

it is crash looping

### Detailed description

Our local timeline isn't self-updating, and I've traced it to the fact that the streaming API is down, and apparently that's because the streaming API can't start up at all right now. I can reproduce this 100% of the time.

### Mastodon instance

wandering.shop

### Mastodon version

v4.2.0

### Technical details

My streaming API configuration:

```yaml
  streaming:
    #build: .
    image: ghcr.io/mastodon/mastodon:v4.2.0
    restart: always
    env_file: .env.production
    environment:
      - STATSD_ADDR=statsd:9125
      - NODE_ENV=production
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - pgbouncer
      - redis
```

Nothing in the env configuration changed between 4.1.9 and 4.2.0.
