### ISSUE TITLE
Make the layout fluid and 100% width in advanced mode

### ISSUE THREAD

**Issue by nd-** [mastodon/mastodon#27695]
### Pitch

I'm always using the multi-columns (advanced) mode, and on a wide desktop monitor the columns are to narrow for a good readability, and the form to write a message is too narrow too.

`.drawer` and `.column` have a fixed width, and a flex-grow: 0, which means they can't get wider.
They could have instead a min width (not fixed), and a flex grow: 1, to occupy 100% of available viewport.

Or something like : 

```css
@media screen and (width >= 631px) {
  .columns-area {
      display: flex;
      width: 100%;
  }
  .columns-area .column,
  .columns-area .drawer {
      flex: 1;
      width: 100%;
  }
}
```
There could be a max-width too, to avoid too large columns on very wide viewports.

Before : 

![image](https://github.com/mastodon/mastodon/assets/5727669/d775ab9b-3d69-402d-9d7a-9959da88fa96)

After : 

![image](https://github.com/mastodon/mastodon/assets/5727669/8d3bfc5b-e428-4677-8d05-2e07dca08a46)

### Motivation

Better usability and readability in advanced mode.
