### ISSUE TITLE
Is STATSD mechanism still supported in Mastodon 4.2.0 / 4.2.1?

### ISSUE THREAD

**Issue by ctrlsill** [mastodon/mastodon#27979]
There are statsd metrics already emitted by Mastodon if you configure it.

You can find a nice article here to setup statsd + Prometheus + Grafana, with a nice dashboard giving you a lot of performance insights: https://ipng.ch/s/articles/2022/11/27/mastodon-3.html

_Originally posted by @renchap in https://github.com/mastodon/mastodon/issues/21354#issuecomment-1448501443_

## Is STATSD mechanism still supported in Mastodon 4.2.0 / 4.2.1?
  I have configured everything as described in the article but Mastodon seems to not emit desired metrics
 
here is my .env config:

````
 # STATSD
STATSD_ADDR=localhost:9125
STATSD_NAMESPACE=Mastodon.production
STATSD_SIDEKIQ=true
````

and my docker-compose stated exporter configured as follows:

````
  statsd_exporter:
    image: prom/statsd-exporter
    container_name: statsd_exporter
    ports:
      - "9102:9102" # Expose the default port for Prometheus metrics
      - "9125:9125/udp" # Expose the default UDP port for StatsD metrics
    command:
      - '--statsd.listen-udp=:9125'
      - '--web.listen-address=:9102'
    volumes:
      - /etc/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--statsd.mapping-config=/etc/prometheus/statsd-mapping.yml'
    networks:
      - external_network
      - internal_network
````  
Exporter seems to work fine, but cannot grab metrics from localhost:9125 :

````
     docker-compose logs -f statsd_exporter
Attaching to statsd_exporter
statsd_exporter      | ts=2023-11-19T14:09:25.228Z caller=main.go:300 level=info msg="Starting StatsD -> Prometheus Exporter" version="(version=0.25.0, branch=HEAD, revision=3855b3e8c99eb94c216bcb254cefefc4ba9cbb8f)"
statsd_exporter      | ts=2023-11-19T14:09:25.228Z caller=main.go:301 level=info msg="Build context" context="(go=go1.19.12, platform=linux/amd64, user=root@c15c3713f3b4, date=20231023-16:35:30, tags=netgo static_build)"
statsd_exporter      | ts=2023-11-19T14:09:25.229Z caller=main.go:350 level=info msg="Accepting StatsD Traffic" udp=:9125 tcp=:9125 unixgram=
statsd_exporter      | ts=2023-11-19T14:09:25.229Z caller=main.go:351 level=info msg="Accepting Prometheus Requests" addr=:9102
````

````
sudo tcpdump -Ani lo port 9125
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on lo, link-type EN10MB (Ethernet), snapshot length 262144 bytes
...
````
when checking localhost:9102/metrics endpoint, it indeed returns some metrics, but these are not what I was expecting:
````
 curl -X GET localhost:9102/metrics
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 1.7543e-05
go_gc_duration_seconds{quantile="0.25"} 2.4421e-05
go_gc_duration_seconds{quantile="0.5"} 2.9033e-05
go_gc_duration_seconds{quantile="0.75"} 3.1204e-05
go_gc_duration_seconds{quantile="1"} 0.00110835
go_gc_duration_seconds_sum 0.002533434
go_gc_duration_seconds_count 46
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 15
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.19.12"} 1
...
````

Do you have some ideas whats wrong in my configuration or have some clues why Mastodon does not emit the metrics (like Sidekiq, Puma, SQL etc.)?
