### ISSUE TITLE
Emoji purge with S3 backend fails

### ISSUE THREAD

**Issue by lonestaritaly** [mastodon/mastodon#28450]
### Steps to reproduce the problem

1. Execute 'tootctl emojy purge' on my instance

### Expected behaviour

Custom Emojis should be purged and then freshly downloaded

### Actual behaviour

the command exits with errors

### Detailed description

Custom emojis have been synced from local storage on disk to Backblaze B2 using rclone.
Because of many emoji not being correctly displayed on web, the goal is to purge them all and make them be refreshed from remote instances.

When I give the "tootctl emoji purge" command, it stays quiet for quite some time (20 minutes and more) and then exits with these errors:

```
# tootctl emoji purge 
DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.

Check the Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
for more information on how to upgrade.
 (called from <main> at /app/www/config/environment.rb:7)

/usr/lib/ruby/3.2.0/net/protocol.rb:237:in `rbuf_fill': end of file reached (Seahorse::Client::NetworkingError)
        from /usr/lib/ruby/3.2.0/net/protocol.rb:199:in `readuntil'
        from /usr/lib/ruby/3.2.0/net/protocol.rb:209:in `readline'
        from /usr/lib/ruby/3.2.0/net/http/response.rb:158:in `read_status_line'
        from /usr/lib/ruby/3.2.0/net/http/response.rb:147:in `read_new'
        from /usr/lib/ruby/3.2.0/net/http.rb:1862:in `block in transport_request'
        from /usr/lib/ruby/3.2.0/net/http.rb:1853:in `catch'
        from /usr/lib/ruby/3.2.0/net/http.rb:1853:in `transport_request'
        from /usr/lib/ruby/3.2.0/net/http.rb:1826:in `request'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/httplog-1.6.2/lib/httplog/adapters/net_http.rb:12:in `block in request'
        from /usr/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/httplog-1.6.2/lib/httplog/adapters/net_http.rb:11:in `request'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/net_http/connection_pool.rb:348:in `request'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/net_http/handler.rb:79:in `block in transmit'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/net_http/handler.rb:133:in `block in session'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/net_http/connection_pool.rb:104:in `session_for'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/net_http/handler.rb:128:in `session'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/net_http/handler.rb:76:in `transmit'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/net_http/handler.rb:50:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/plugins/content_length.rb:24:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/plugins/request_callback.rb:118:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/plugins/s3_signer.rb:73:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/plugins/s3_host_id.rb:17:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/xml/error_handler.rb:10:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/sign.rb:49:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/transfer_encoding.rb:26:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:12:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/plugins/s3_signer.rb:48:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/plugins/redirects.rb:20:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/user_agent.rb:37:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/http_checksum.rb:19:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/endpoint_pattern.rb:30:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:136:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/request_compression.rb:94:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/plugins/expect_100_continue.rb:23:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/plugins/bucket_name_restrictions.rb:21:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/rest/handler.rb:10:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/recursion_detection.rb:18:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/plugins/endpoints.rb:41:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/plugins/endpoint.rb:47:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/param_validator.rb:26:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/plugins/dualstack.rb:21:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/plugins/accelerate.rb:43:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/plugins/request_callback.rb:89:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/request.rb:72:in `send_request'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/poller.rb:66:in `block in send_request'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/user_agent.rb:28:in `feature'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/poller.rb:65:in `send_request'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/poller.rb:51:in `call'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:107:in `block in poll'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:104:in `loop'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:104:in `poll'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:94:in `block (2 levels) in wait'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:93:in `catch'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:93:in `block in wait'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:92:in `catch'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:92:in `wait'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/waiters.rb:200:in `wait'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/object.rb:461:in `block in wait_until_exists'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/user_agent.rb:28:in `feature'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/object.rb:460:in `wait_until_exists'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/object.rb:441:in `exists?'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/kt-paperclip-7.2.1/lib/paperclip/storage/s3.rb:325:in `exists?'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/kt-paperclip-7.2.1/lib/paperclip/attachment.rb:563:in `block in queue_all_for_delete'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/kt-paperclip-7.2.1/lib/paperclip/attachment.rb:562:in `map'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/kt-paperclip-7.2.1/lib/paperclip/attachment.rb:562:in `queue_all_for_delete'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/kt-paperclip-7.2.1/lib/paperclip/has_attached_file.rb:93:in `block in add_active_record_callbacks'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:448:in `instance_exec'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:448:in `block in make_lambda'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:202:in `block (2 levels) in halting'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:707:in `block (2 levels) in default_terminator'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:706:in `catch'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:706:in `block in default_terminator'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:203:in `block in halting'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:598:in `block in invoke_before'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:598:in `each'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:598:in `invoke_before'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:109:in `run_callbacks'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:952:in `_run_destroy_callbacks'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/callbacks.rb:423:in `destroy'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/transactions.rb:305:in `block in destroy'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/transactions.rb:365:in `block in with_transaction_returning_status'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/transactions.rb:305:in `destroy'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation.rb:610:in `each'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation.rb:610:in `destroy_all'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation/batches.rb:396:in `block in batch_on_unloaded_relation'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation/batches.rb:372:in `loop'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation/batches.rb:372:in `batch_on_unloaded_relation'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation/batches.rb:269:in `in_batches'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation/batches/batch_enumerator.rb:96:in `each'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation/batches/batch_enumerator.rb:96:in `each'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation/batches/batch_enumerator.rb:86:in `destroy_all'
        from /app/www/lib/mastodon/cli/emoji.rb:124:in `purge'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /app/www/bin/tootctl:9:in `block in <main>'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy/strategy.rb:60:in `wrap'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy.rb:154:in `strategy'
        from /app/www/bin/tootctl:8:in `<main>'
/app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:114:in `block in poll': stopped waiting due to an unexpected error: end of file reached (Aws::Waiters::Errors::UnexpectedError)
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:104:in `loop'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:104:in `poll'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:94:in `block (2 levels) in wait'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:93:in `catch'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:93:in `block in wait'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:92:in `catch'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/waiters/waiter.rb:92:in `wait'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/waiters.rb:200:in `wait'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/object.rb:461:in `block in wait_until_exists'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/user_agent.rb:28:in `feature'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/object.rb:460:in `wait_until_exists'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/object.rb:441:in `exists?'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/kt-paperclip-7.2.1/lib/paperclip/storage/s3.rb:325:in `exists?'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/kt-paperclip-7.2.1/lib/paperclip/attachment.rb:563:in `block in queue_all_for_delete'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/kt-paperclip-7.2.1/lib/paperclip/attachment.rb:562:in `map'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/kt-paperclip-7.2.1/lib/paperclip/attachment.rb:562:in `queue_all_for_delete'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/kt-paperclip-7.2.1/lib/paperclip/has_attached_file.rb:93:in `block in add_active_record_callbacks'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:448:in `instance_exec'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:448:in `block in make_lambda'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:202:in `block (2 levels) in halting'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:707:in `block (2 levels) in default_terminator'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:706:in `catch'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:706:in `block in default_terminator'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:203:in `block in halting'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:598:in `block in invoke_before'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:598:in `each'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:598:in `invoke_before'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:109:in `run_callbacks'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:952:in `_run_destroy_callbacks'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/callbacks.rb:423:in `destroy'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/transactions.rb:305:in `block in destroy'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/transactions.rb:365:in `block in with_transaction_returning_status'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/transactions.rb:305:in `destroy'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation.rb:610:in `each'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation.rb:610:in `destroy_all'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation/batches.rb:396:in `block in batch_on_unloaded_relation'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation/batches.rb:372:in `loop'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation/batches.rb:372:in `batch_on_unloaded_relation'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation/batches.rb:269:in `in_batches'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation/batches/batch_enumerator.rb:96:in `each'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation/batches/batch_enumerator.rb:96:in `each'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/relation/batches/batch_enumerator.rb:86:in `destroy_all'
        from /app/www/lib/mastodon/cli/emoji.rb:124:in `purge'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /app/www/bin/tootctl:9:in `block in <main>'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy/strategy.rb:60:in `wrap'
        from /app/www/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy.rb:154:in `strategy'
        from /app/www/bin/tootctl:8:in `<main>'


````

Any hint on what could be wrong?

docker compose for the instance:
```
version: "2.1"
services:
  mastodon:
    image: lscr.io/linuxserver/mastodon:glitch
    container_name: mastodon
    hostname: xxxx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - LOCAL_DOMAIN=xxxx
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=xxxx
      - DB_HOST=db
      - DB_USER=xxxx
      - DB_NAME=xxxx
      - DB_PASS=xxxx
      - DB_PORT=5432
      - ES_ENABLED=true
      - SECRET_KEY_BASE=xxxx
      - OTP_SECRET=xxxx
      - VAPID_PRIVATE_KEY=xxxx
      - VAPID_PUBLIC_KEY=xxxx
      - SMTP_SERVER=xxxx
      - SMTP_PORT=587
      - SMTP_LOGIN=xxxx
      - SMTP_PASSWORD=xxxx
      - SMTP_FROM_ADDRESS=xxxx
      - SMTP_SSL=false
      - SMTP_TLS=false
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=none
      - S3_ENABLED=true
      - WEB_DOMAIN=xxxx
      - ES_HOST=http://elastic #optional
      - ES_PORT=9200 #optional
      - ES_USER=elastic #optional
      - ES_PASS=xxxx #optional
      - ES_PRESET=single_node_cluster
      - S3_BUCKET=xxxx
      - AWS_ACCESS_KEY_ID=xxxx
      - AWS_SECRET_ACCESS_KEY=xxxx
      - S3_HOSTNAME=s3.us-east-005.backblazeb2.com
      - S3_ENDPOINT=https://s3.us-east-005.backblazeb2.com
      - S3_PROTOCOL=https
      - S3_OPEN_TIMEOUT=20
      - S3_READ_TIMEOUT=20 
      - SIDEKIQ_THREADS=15
      - DB_POOL=20
      - NO_CHOWN=true
      - ALLOWED_PRIVATE_ADDRESSES=192.168.100.0/24,10.100.0.0/16
      - LIBRE_TRANSLATE_ENDPOINT=http://libretranslate:5000

    volumes:
      - /srv/docker/mastodon/config:/config
    ports:
      - 6880:80
      - 6443:443
    restart: unless-stopped
    networks:
      - redis_net
      - docker-mastodon_default
    depends_on:
      - db

  db:
    restart: always
    image: postgres:14-alpine
    container_name: mastodon-postgres
    shm_size: 256mb
    networks:
      - docker-mastodon_default
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'mastodon']
    volumes:
      - /srv/docker/mastodon/postgres14:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_USER=xxxx'
      - 'POSTGRES_PASSWORD=xxxx'
      - 'POSTGRES_DB=xxxx'
      
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - LT_DEBUG=true
      - LT_UPDATE_MODELS=true
      - LT_SUGGESTIONS=false
      - LT_METRICS=true
      - LT_THREADS=12
      - LT_FRONTEND_TIMEOUT=2000

    networks:
      - docker-mastodon_default

  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    mem_limit: "1G"
    restart: unless-stopped
    environment:
      - ELASTIC_PASSWORD=xxxx
      - "xpack.license.self_generated.type=basic"
      - "xpack.security.enabled=false"
      - "xpack.watcher.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.ml.enabled=false"
      - "bootstrap.memory_lock=true"
      - "cluster.name=es-mastodon"
      - "discovery.type=single-node"
      - "thread_pool.write.queue_size=1000"
    volumes:
      - /srv/docker/mastodon/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - docker-mastodon_default
      
networks:
  redis_net:
    external: true
  docker-mastodon_default:
    external: false
```

### Mastodon version

v4.3.0-alpha.0+glitch

### Technical details

linuxserver mastodon-glitch docker container
Backblaze B2 S3 Compatible API for S3 media storage
