### ISSUE TITLE
Vagrant machine uses deprecated nodesource setup script

### ISSUE THREAD

**Issue by cortices** [mastodon/mastodon#28877]
### Steps to reproduce the problem

1. Install prerequisites
2. delete old vagrant machines (`vagrant destroy`)
3. Run `vagrant up`

### Expected behaviour

reasonable boot

### Actual behaviour

warning from nodesource script

### Detailed description

creating a fresh vagrant box. The client box setup will pause with a large deprecation notice as per below:

````
default: ================================================================================
    default: ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
    default: ================================================================================
    default: 
    default:                            SCRIPT DEPRECATION WARNING
    default: 
    default: 
    default:   This script, located at https://deb.nodesource.com/setup_X, used to
    default:   install Node.js is deprecated now and will eventually be made inactive.
    default: 
    default:   Please visit the NodeSource distributions Github and follow the
    default:   instructions to migrate your repo.
    default:   https://github.com/nodesource/distributions
    default: 
    default:   The NodeSource Node.js Linux distributions GitHub repository contains
    default:   information about which versions of Node.js and which Linux distributions
    default:   are supported and how to install it.
    default:   https://github.com/nodesource/distributions
    default: 
    default: 
    default:                           SCRIPT DEPRECATION WARNING
    default: 
    default: ================================================================================
    default: ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
    default: ================================================================================
    default: 
    default: TO AVOID THIS WAIT MIGRATE THE SCRIPT
    default: Continuing in 60 seconds (press Ctrl-C to abort) ...
````

### Mastodon instance

N/A

### Mastodon version

main glitchsoc

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (3.2.2)
- Node.js version: (20)
