### ISSUE TITLE
FATAL:  database "mastodon" does not exist

### ISSUE THREAD

**Issue by Slevin7** [mastodon/mastodon#29162]
### Steps to reproduce the problem

Somehow I always get the error FATAL: database "mastodon" does not exist.

Mastdon itself actually works as it should, I just don't know what's wrong.

my docker-compose (excerpt)
```
services:
  db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - mastodon
    volumes:
      - ./postgres14:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mastodon_production
      POSTGRES_USER: mastodon
```

the .env 
```
# PostgreSQL
# ----------
DB_HOST=mastodon-db-1
DB_USER=mastodon
DB_NAME=mastodon_production
DB_PASS=password
DB_PORT=5432
```

so no db named mastodon,
should i just create tis db and everything is fine?
I'm just worried that I'll kill my instance if I just put a new database in there

### Expected behaviour

no error

### Actual behaviour

FATAL:  database "mastodon" does not exist

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)
