### ISSUE TITLE
Broken Web ui for new session

### ISSUE THREAD

**Issue by papalouf** [mastodon/mastodon#29397]
### Steps to reproduce the problem

Open a new browser tab with cleared caches/cookies.
Join https://mastodon.ptolemaios.fr/
You face "We're sorry, but something went wrong on our end." error page. 

### Expected behaviour

You should see the "home" page of the instance

### Actual behaviour

You face "We're sorry, but something went wrong on our end." error page. 

### Detailed description

I tried to open a new session of my mastodon instance on my gf's mac to manage some configuration but I always got error 500 "We're sorry, but something went wrong on our end." error page, for each page i try to reach. 
I tried to redeploy my docker compose stack after cleaning all volumes (except postgreSQL one) but faced the same issue. 
But strangely, from devices where i've got opened sessions on a browser (as my smartphone), I can 100% normally browse the webui of my instance. 
And no problem either to connect to it from my Ivory client (everything works correctly), it's only the webui from a device never connected to my mastodon instance that have issues. 

### Mastodon instance

mastodon.ptolemaios.fr

### Mastodon version

v4.2.8

### Browser name and version

Arc 1.31.1, Safari 17.3.1, Firefox 123.0 (fresh install), Google Chrome 122.0.6261.69 (fresh install)

### Operating system

macOS Sonoma 14.3.1

### Technical details

I use the docker-compose.yaml below. 

```yaml
version: '3'
services:
  ptolemaios_mastodon_postgres:
    container_name: ptolemaios_mastodon_postgres
    stop_signal: SIGINT
    image: bitnami/postgresql:14
    restart: always
    shm_size: 256mb
    environment:
      #- POSTGRESQL_DATABASE=${POSTGRESQL_DB}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
      - BITNAMI_DEBUG=true
    volumes:
      - /var/www/Mastodon/postgresql:/bitnami/postgresql
      - /var/www/Mastodon/postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - /var/www/Mastodon/postgresql/docker-entrypoint-preinitdb.d:/docker-entrypoint-preinitdb.d
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    networks:
      - ptolemaios_mastodon_backend

  ptolemaios_mastodon_redis:
    container_name: ptolemaios_mastodon_redis
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_IO_THREADS_DO_READS=yes
      - REDIS_IO_THREADS=6
      - REDIS_AOF_ENABLED=no
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - ptolemaios_mastodon_backend

  ptolemaios_mastodon_web:
    image: ghcr.io/mastodon/mastodon:${MASTODON_VERSION}
    container_name: ptolemaios_mastodon_web
    restart: always
    environment: 
      - LOCAL_DOMAIN=${LOCAL_DOMAIN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${POSTGRESQL_USER}
      - DB_NAME=${POSTGRESQL_DB}
      - DB_PASS=${POSTGRESQL_PASSWORD}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - OTP_SECRET=${OTP_SECRET}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_LOGIN=${SMTP_LOGIN}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - S3_ENABLED=${S3_ENABLED}
      - IP_RETENTION_PERIOD=${IP_RETENTION_PERIOD}
      - SESSION_RETENTION_PERIOD=${SESSION_RETENTION_PERIOD}
      - WEB_CONCURRENCY=4
      - MAX_THREADS=6
    command: bundle exec puma -C config/puma.rb
    networks:
      - ptolemaios_mastodon_frontend
      - ptolemaios_mastodon_backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    depends_on:
      - ptolemaios_mastodon_postgres
      - ptolemaios_mastodon_redis
    # - ptolemaios_mastodon_es
    volumes:
    - /var/www/Mastodon/public/system:/mastodon/public/system

  ptolemaios_mastodon_streaming:
    container_name: ptolemaios_mastodon_streaming
    image: ghcr.io/mastodon/mastodon:${MASTODON_VERSION}
    restart: always
    environment: 
      - LOCAL_DOMAIN=${LOCAL_DOMAIN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${POSTGRESQL_USER}
      - DB_NAME=${POSTGRESQL_DB}
      - DB_PASS=${POSTGRESQL_PASSWORD}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - OTP_SECRET=${OTP_SECRET}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_LOGIN=${SMTP_LOGIN}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - S3_ENABLED=${S3_ENABLED}
      - IP_RETENTION_PERIOD=${IP_RETENTION_PERIOD}
      - SESSION_RETENTION_PERIOD=${SESSION_RETENTION_PERIOD}
    command: node ./streaming
    networks:
      - ptolemaios_mastodon_frontend
      - ptolemaios_mastodon_backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']
    depends_on:
      - ptolemaios_mastodon_postgres
      - ptolemaios_mastodon_redis

  ptolemaios_mastodon_sidekiq:
    container_name: ptolemaios_mastodon_sidekiq
    image: ghcr.io/mastodon/mastodon:${MASTODON_VERSION}
    restart: always
    environment: 
      - LOCAL_DOMAIN=${LOCAL_DOMAIN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${POSTGRESQL_USER}
      - DB_NAME=${POSTGRESQL_DB}
      - DB_PASS=${POSTGRESQL_PASSWORD}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - OTP_SECRET=${OTP_SECRET}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_LOGIN=${SMTP_LOGIN}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - S3_ENABLED=${S3_ENABLED}
      - IP_RETENTION_PERIOD=${IP_RETENTION_PERIOD}
      - SESSION_RETENTION_PERIOD=${SESSION_RETENTION_PERIOD}
      - SIDEKIQ_CONCURRENCY=8
    command: bundle exec sidekiq
    depends_on:
      - ptolemaios_mastodon_postgres
      - ptolemaios_mastodon_redis
    networks:
      - ptolemaios_mastodon_frontend
      - ptolemaios_mastodon_backend
    volumes:
      - /var/www/Mastodon/public/system:/mastodon/public/system
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]

networks:
  ptolemaios_mastodon_frontend:
    external: true
    name: internal_loop
  ptolemaios_mastodon_backend:
    external: false
    name: ptolemaios_mastodon_backend
```
