### ISSUE TITLE
Concider: Replacement of Redis due to license change

### ISSUE THREAD

**Issue by soupglasses** [mastodon/mastodon#29729]
### Pitch

[Redis recently relicenced their software suite](https://redis.com/blog/redis-adopts-dual-source-available-licensing/) to a [no longer be free software license](https://lwn.net/Articles/966133/) effectively making it a proprietary dependency to running Mastodon.

I propose changing it.

We can continue to use Redis-compatible key-value stores. This is low effort and requires no code changes, and is mostly a testing and documentation change.

1. [KeyDB](https://github.com/Snapchat/KeyDB), a multithreaded fork of Redis, funded and developed by Snap Inc. BSD-3 licensed, should work basically as a drop in replacement today. Previous discussion: #13204
2. [KVRocks](https://github.com/apache/kvrocks), a distributed key value store, built on top of RocksDB to be compatible with the Redis protocol. Apache 2.0 licensed.
3. [Redict](https://codeberg.org/redict/redict), hard fork of Redis 7.2.4 before the license change, made by Drew DeVault. LGPL 3.0-only licensed.

Now, alternatively, we could look into replacing Redis as a protocol entirely with another key-value store. This is a much larger task, but to exhaust the options available notable alternatives here would be:

4. [Memcached](https://github.com/memcached/memcached), A mature but simpler key-value store. BSD-3 licensed.
5. [RocksDB](https://github.com/facebook/rocksdb/), A persistent key-value store, funded and developed by Facebook/Meta. Dual-licensed as GPL 2.0-only and Apache 2.0.
6. [Ignite](https://github.com/apache/ignite), "a distributed database for high-performance computing with in-memory speed". Apache 2.0 licensed.

### Motivation

Mastodon is an open source project, depending upon non-opensource projects would remove the possibility to run mastodon with open source software, which is now the current state after the Redis license change. Therefore this default should be changed officially.

**Comment by soupglasses** [comment]
A practical issue is that Linux distributions will be in the next few months be looking into removing Redis. So bare-metal installs will become more difficult.

**Comment by viktorix** [comment]
Another new fork by former Redis contributors (and AWS employees) is
[placeholderkv](https://github.com/placeholderkv/placeholderkv/) (they're looking for a permanent name)

**Comment by nomad-geek** [comment]
Adding my vote to this change. Support Free OSS.

**Comment by Morethanevil** [comment]
I vote for this change too. Valkey seems to be the most promising candidate

**Comment by thomas992** [comment]
I second Valkey. KeyDB is acceptable too.

**Comment by Morethanevil** [comment]
Any news on this?

**Comment by madolson** [comment]
Is there any update on this? It looks like the [docker compose](https://github.com/mastodon/mastodon/blob/46c43d263c44d2ae1e896bca3dd8b0195989240d/docker-compose.yml#L21) file is now relying on the proprietary version of Redis. (The license was formally changed in 7.4, which is now the head of 7-alpine). The snapshots in Redis 7.4 are not compatible with other Valkey or other engines, so maybe at the very least that file should pin the version to 7.2-alpine to retain compatibility.

**Comment by yingziwu** [comment]
Fedora release 41 has switched from Redis to Valkey
https://fedoraproject.org/wiki/Changes/Replace_Redis_With_Valkey

Arch Linux has also switched from Redis to Valkey
https://archlinux.org/news/valkey-to-replace-redis-in-the-extra-repository/

**Comment by evrial** [comment]
@ClearlyClaire any input on this?

**Comment by edsu** [comment]
Didn't Redis recently switch to AGPLv3? 

https://redis.io/blog/agplv3/

**Comment by SleepingPanda** [comment]
That was because everyone dumped them when they switched to a non-FOSS license. Even if they adopted AGPL, that doesn't mean they're suddenly re-included in the Fedora and Arch repos. Also, they didn't "switch" anything per their wording on your link: 

> Adding the OSI-approved [AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html) as an additional licensing option for Redis, starting with Redis 8 (available now)

That AGPL license option is only for Redis 8 and above.

**Comment by evrial** [comment]
Yeah copyleft turn was done thanks to the Valkey after 14 months.

**Comment by ClearlyClaire** [comment]
Mastodon should be compatible with Valkey, and iirc recent-ish versions of Redis become free software 4 years after release, whereas Redis 8 is now free software again. I don't think we need to make a change here.

**Comment by Morethanevil** [comment]
Mastodon runs fine with Valkey 8.1 and the current unstable (9). I use 8.1 for my production server. If the docker-compose is updated the next time, you could replace `redis:7-alpine` with `valkey/valkey:8-alpine`


Nobodys knows if redis ever does this again.

**Comment by evrial** [comment]
> Mastodon should be compatible with Valkey

Can you pls write this in readme to make it official?

**Comment by SleepingPanda** [comment]
@Morethanevil @ClearlyClaire the problems are:

- Redis made their data format proprietary after Redis 7.2 which prevents exports from being imported to Valkey and other previously compatible key-value databases (without using hacked-together third-party conversion tools).
- Even though Redis now has an AGPL option, that effectively changes nothing for a chunk of server admins because Redis is no longer included in FOSS repositories.

What we're asking for is official movement to Valkey to keep the Mastodon stack truly free.

**Comment by rasos** [comment]
Running now two Mastodon instances with `image: docker.io/valkey/valkey:9.1.0` on kubernetes. Our reason to migrate was that we had been using  `image: docker.io/bitnamilegacy/redis:8.2.1` which did not receive any further updates. 

As valkey was forked from Redis 7.2, the DB is not compatible and needs to be deleted. Here is the one time job I had to apply - if it might help somebody also migrating on k8s: 

```
# One-off job: clears the redis-data PVC ahead of the Redis -> Valkey
# swap. Valkey forked at Redis 7.2.4 and isn't guaranteed to load an RDB
# file written by Redis 8.2 - on an incompatible file valkey-server exits
# instead of starting, so the new pod would crash-loop. This volume only
# holds cache + Sidekiq queue state, safe to drop.
#
# Do not apply this via `kubectl apply -k` together with the rest of the
# overlay: redis-data is ReadWriteOnce, so this job, the old prod-redis
# pod, and the new mastodon-valkey pod can't all hold it at once. Apply it
# standalone after scaling prod-redis to 0, then delete it once it has
# run. 
apiVersion: batch/v1
kind: Job
metadata:
  name: valkey-data-reset
spec:
  backoffLimit: 1
  template:
    metadata:
      name: valkey-data-reset
    spec:
      restartPolicy: Never
      containers:
        - name: valkey-data-reset
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - "rm -rf /data/dump.rdb /data/appendonlydir /data/appendonly.aof* && echo cleared"
          volumeMounts:
            - name: redis-volume
              mountPath: /data
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-data
```
