### ISSUE TITLE
Advanced web interface is slightly too wide for common screen resolution (1080p)

### ISSUE THREAD

**Issue by lucaswerkmeister** [mastodon/mastodon#32316]
### Pitch

When using the advanced web interface with five columns – e.g. compose / search (the “drawer”, IIUC?), home, notifications, local timeline, and focused post / getting started – the resulting interface is 1950px wide, which is just slightly more than the 1920px width you get with some common screen resolutions (1920x1080, or 3840x2160 at 200% zoom). I think it would be reasonable to reduce the width a bit, e.g. by shaving 30px off the first column:

```css
.drawer {
    max-width: 320px; /* instead of 350px; .column has 400px btw */
}
```

### Motivation

This would avoid a distracting horizontal scrollbar (and visual truncation at the right edge) for users using a common screen resolution.
