### ISSUE TITLE
Strange text overlay on mouseover on toot with "read more"

### ISSUE THREAD

**Issue by fluffy-critter** [mastodon/mastodon#32429]
### Steps to reproduce the problem

This happened when [this toot](https://plush.city/@faithisleaping@anarres.family/113290273792806041) appeared on my timeline, and I hovered my mouse over the main text (above the "read more"). It appears to be the "more text" expanded out on top of the rest of the UI.

![image](https://github.com/user-attachments/assets/06b3de4e-775e-454e-885b-3824a5ba95b8)

### Expected behaviour

This rendering issue should not have occurred

### Actual behaviour

"More" text appears on top of the UI below the toot it came from

### Mastodon instance

plush.city

### Mastodon version

v4.3.0

### Browser name and version

Firefox 131.0.2

### Operating system

macOS 14.6.1

**Comment by renchap** [comment]
I have this post in my timeline as well, but I am not able to reproduce this. The show more button works correctly, and there is no overlay text visible

<img width="391" alt="image" src="https://github.com/user-attachments/assets/4ab96760-1c84-4a4e-8d05-3db9bf631a9f">

I checked and your instance has some custom styles applied, that I think are causing the issue. Specifically:

```css
/* Fix overflow for the above emojo zoomers */
.reply-indicatorcontent, .statuscontent:hover,
.edit-indicator__content:hover, .reply-indicator__content:hover, .status__content:hover, /* Mastodon 4.3.0 */
.notification div.status.muted .status__content p:hover,
.notification div.status.muted .status__content p img:hover{
    overflow: visible !important;
    opacity: 1 !important;
}

/* Skip above fix for toots with additional content hidden behind a read more */
.reply-indicatorcontent, .statuscontent.status__content--collapsed:hover {
    overflow: hidden !important;
}
```
