### ISSUE TITLE
TrueNAS Installation - streaming container exits with Module Not Found error

### ISSUE THREAD

**Issue by InfiniteBed** [mastodon/mastodon#32985]
### Steps to reproduce the problem

1. Follow [this tutorial](https://gist.github.com/TrillCyborg/84939cd4013ace9960031b803a0590c4) on the TrueNAS CLI, without running `docker-compose up -d`
2. Transfer docker-compose to TrueNAS's native applications page
![Image](https://github.com/user-attachments/assets/be2c5d09-3278-49b5-b5f6-02a7b52a946e)
3. Run application
![Image](https://github.com/user-attachments/assets/e0ec07d8-d4f0-443a-b94b-980c82d079f7)

### Expected behaviour

Mastodon should have deployed without issue.

### Actual behaviour

streaming container exits immediately, stating `Cannot find module ... streaming/index.js`

### Detailed description

I am absolutely certain that the container is pointing to the correct location.
Permission errors are almost certainly nonexistent.

### Mastodon instance

social.homeschoolperk.com

### Mastodon version

v4.3.1

### Environment

- Operating system: TrueNAS Scale Electric Eel 24.10 (based on FreeBSD, ZFS filesystem)
- Ruby version: v3.3.5 
- Node.js version: v20.18.0

### Technical details

Below is the streaming container error.
```
2024-11-19 18:50:45.172591+00:00Node.js v20.18.0
2024-11-19 18:51:46.133817+00:00node:internal/modules/cjs/loader:1228
2024-11-19 18:51:46.133955+00:00throw err;
2024-11-19 18:51:46.134003+00:00^
2024-11-19 18:51:46.134019+00:002024-11-19T18:51:46.134019639Z
2024-11-19 18:51:46.134031+00:00Error: Cannot find module '/mnt/Lake/Starboard/Mastodon/mastodon/streaming/index.js'
2024-11-19 18:51:46.134043+00:00at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
2024-11-19 18:51:46.134055+00:00at Module._load (node:internal/modules/cjs/loader:1051:27)
2024-11-19 18:51:46.134080+00:00at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
2024-11-19 18:51:46.134092+00:00at node:internal/main/run_main_module:28:49 {
2024-11-19 18:51:46.134103+00:00code: 'MODULE_NOT_FOUND',
2024-11-19 18:51:46.134115+00:00requireStack: []
2024-11-19 18:51:46.134139+00:00}
```
And here is my compose file
```
networks:
  external_network: Null
  internal_network:
    internal: True
services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-U'
        - postgres
    image: postgres:14-alpine
    networks:
      - internal_network
    restart: always
    shm_size: 256mb
    volumes:
      - >-
        /mnt/Lake/Starboard/Mastodon/mastodon/postgres14:/var/lib/postgresql/data
  redis:
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
    image: redis:7-alpine
    networks:
      - internal_network
    restart: always
    volumes:
      - /mnt/Lake/Starboard/Mastodon/mastodon/redis:/data
  sidekiq:
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    env_file: /mnt/Lake/Starboard/Mastodon/mastodon/.env.production
    healthcheck:
      test:
        - CMD-SHELL
        - ps aux | grep '[s]idekiq 6' || false
    image: ghcr.io/mastodon/mastodon:v4.3.1
    networks:
      - external_network
      - internal_network
    restart: always
    volumes:
      - >-
        /mnt/Lake/Starboard/Mastodon/mastodon/public/system:/mastodon/public/system
  streaming:
    build: /mnt/Lake/Starboard/Mastodon/mastodon/.
    command: node /mnt/Lake/Starboard/Mastodon/mastodon/streaming/index.js
    depends_on:
      - db
      - redis
    env_file: /mnt/Lake/Starboard/Mastodon/mastodon/.env.production
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          curl -s --noproxy localhost localhost:4000/api/v1/streaming/health |
          grep -q 'OK' || exit 1
    image: ghcr.io/mastodon/mastodon-streaming
    networks:
      - external_network
      - internal_network
    ports:
      - 127.0.0.1:4000:4000
    restart: always
  web:
    build: /mnt/Lake/Starboard/Mastodon/mastodon/.
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
      - redis
    env_file: /mnt/Lake/Starboard/Mastodon/mastodon/.env.production
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          curl -s --noproxy localhost localhost:3000/health | grep -q 'OK' ||
          exit 1
    image: ghcr.io/mastodon/mastodon
    networks:
      - external_network
      - internal_network
    ports:
      - 127.0.0.1:3000:3000
    restart: always
    volumes:
      - >-
        /mnt/Lake/Starboard/Mastodon/mastodon/public/system:/mastodon/public/system
```

**Comment by renchap** [comment]
Your compose file is incorrect for the streaming service, it does not build the correct container.

Either remove the `build` lines from this file to use the pre-build images (recommended), or adjust it to match our current compose file (see https://github.com/mastodon/mastodon/blob/main/docker-compose.yml#L83C3-L85C19)

**Comment by renchap** [comment]
Your compose file is still not using the streaming image. I am not sure why but this is an issue with your setup. Did you run `docker compose down` then `docker compose up`? You should not have to use those `build:` attributes in your compose file.

**Comment by InfiniteBed** [comment]
I did try both the modified build file as well as removing the build attributes.
TrueNAS is intended to handle all the docker commands on its backend. I assume when a compose file is updated,  it composes down and up with the new compose file. 
Here is how the compose looks now.
```
networks:
  external_network: Null
  internal_network:
    internal: True
services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-U'
        - postgres
    image: postgres:14-alpine
    networks:
      - internal_network
    restart: always
    shm_size: 256mb
    volumes:
      - >-
        /mnt/Lake/Starboard/Mastodon/mastodon/postgres14:/var/lib/postgresql/data
  redis:
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
    image: redis:7-alpine
    networks:
      - internal_network
    restart: always
    volumes:
      - /mnt/Lake/Starboard/Mastodon/mastodon/redis:/data
  sidekiq:
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    env_file: /mnt/Lake/Starboard/Mastodon/mastodon/.env.production
    healthcheck:
      test:
        - CMD-SHELL
        - ps aux | grep '[s]idekiq 6' || false
    image: ghcr.io/mastodon/mastodon:v4.3.1
    networks:
      - external_network
      - internal_network
    restart: always
    volumes:
      - >-
        /mnt/Lake/Starboard/Mastodon/mastodon/public/system:/mastodon/public/system
  streaming:
    command: node /mnt/Lake/Starboard/Mastodon/mastodon/streaming/index.js
    depends_on:
      - db
      - redis
    env_file: /mnt/Lake/Starboard/Mastodon/mastodon/.env.production
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          curl -s --noproxy localhost localhost:4000/api/v1/streaming/health |
          grep -q 'OK' || exit 1
    image: ghcr.io/mastodon/mastodon-streaming:v4.3.1
    networks:
      - external_network
      - internal_network
    ports:
      - 127.0.0.1:4000:4000
    restart: always
  web:
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
      - redis
    env_file: /mnt/Lake/Starboard/Mastodon/mastodon/.env.production
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          curl -s --noproxy localhost localhost:3000/health | grep -q 'OK' ||
          exit 1
    image: ghcr.io/mastodon/mastodon
    networks:
      - external_network
      - internal_network
    ports:
      - 127.0.0.1:3000:3000
    restart: always
    volumes:
      - >-
        /mnt/Lake/Starboard/Mastodon/mastodon/public/system:/mastodon/public/system
```
