### ISSUE TITLE
Mastodon server cannot connect to SMTP (docker-compose)

### ISSUE THREAD

**Issue by revsuine** [mastodon/mastodon#33073]
### Steps to reproduce the problem

So I cannot get connection to my SMTP server working with Mastodon. The SMTP server is working normally, and I've tested connecting to it and sending email via a mail client (Evolution) and verified that it's working, as well as using sendmail.

I have Postfix running on a host machine, and am trying to use Mastodon inside a Docker container with docker-compose.

I am using the same SMTP settings on both successfully sending mail with Evolution and the failures I'm getting with Mastodon.

Trying port 587 gives me

```
E-mail could not be sent with this configuration, try again.          
454 4.7.0 Temporary authentication failure: generic failure 
```

and port 465 gives me the different error of

```
E-mail could not be sent with this configuration, try again.                                                                                                                                                                       
Net::ReadTimeout with #<TCPSocket:(closed)>
```

My settings are

```
SMTP_SERVER=<my SMTP server domain>
SMTP_PORT=<465/587>
SMTP_LOGIN=noreply
SMTP_PASSWORD=
SMTP_AUTH_METHOD=plain
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_ENABLE_STARTTLS=auto
```

I noticed that when using port 587, the following appears in my postfix log:

```
Nov 26 02:32:34 revsuine postfix/submission/smtpd[26833]: connect from unknown[IP]
Nov 26 02:32:34 revsuine postfix/submission/smtpd[26833]: Anonymous TLS connection established from unknown[IP]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (prime256v1) server-digest SHA256
Nov 26 02:32:34 revsuine postfix/submission/smtpd[26833]: warning: SASL authentication failure: Could not open /etc/sasl2/sasldb2: gdbm_errno=3
Nov 26 02:32:34 revsuine postfix/submission/smtpd[26833]: warning: SASL authentication failure: Password verification failed
Nov 26 02:32:34 revsuine postfix/submission/smtpd[26833]: warning: unknown[IP]: SASL PLAIN authentication failed: generic failure, sasl_username=noreply
Nov 26 02:32:34 revsuine postfix/submission/smtpd[26833]: lost connection after AUTH from unknown[IP]
Nov 26 02:32:34 revsuine postfix/submission/smtpd[26833]: disconnect from unknown[IP] ehlo=2 starttls=1 auth=0/1 commands=3/4
```

It seems like `SASL authentication failure: Could not open /etc/sasl2/sasldb2: gdbm_errno=3` might indicate what the issue is, but I don't know how to fix it. Any pointers are appreciated.

I'm on Alpine Linux v3.20.3, using Mastodon v4.3.1.

I use UFW with [ufw-docker](https://github.com/chaifeng/ufw-docker) as my firewall but I don't think it's a firewall issue, as I tried disabling UFW and the issue still persisted. Also, Mastodon was able to connect to Postfix in the above logs, so it's not getting outright blocked.

I've also tried the send email with localhost option which also didn't work.

Additional info:

When I was wondering if it was a Mastodon issue or not, I tried connecting to an SMTP server of an external email account I had. I got the same error with port 465, but it worked on port 587.

To reproduce:

I'm not sure if this can be reproduced as it's likely some quirk of my system I need to hunt down.

Set up a Postfix server with a user you can authenticate with username and password to send email via either ports 467 or 587.

Use the following `docker-compose.yml`:

```yaml
# This file is designed for production server deployment, not local development work
# For a containerized local dev environment, see: https://github.com/mastodon/mastodon/blob/main/README.md#docker

services:
  db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./postgres14:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis:/data

  # es:
  #   restart: always
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true"
  #     - "xpack.license.self_generated.type=basic"
  #     - "xpack.security.enabled=false"
  #     - "xpack.watcher.enabled=false"
  #     - "xpack.graph.enabled=false"
  #     - "xpack.ml.enabled=false"
  #     - "bootstrap.memory_lock=true"
  #     - "cluster.name=es-mastodon"
  #     - "discovery.type=single-node"
  #     - "thread_pool.write.queue_size=1000"
  #   networks:
  #      - external_network
  #      - internal_network
  #   healthcheck:
  #      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
  #   volumes:
  #      - ./elasticsearch:/usr/share/elasticsearch/data
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   ports:
  #     - '127.0.0.1:9200:9200'

  web:
    # You can uncomment the following line if you want to not use the prebuilt image, for example if you have local code changes
    # build: .
    image: ghcr.io/mastodon/mastodon:v4.3.1
    restart: always
    env_file: .env.production
    command: bundle exec puma -C config/puma.rb
    networks:
      - external_network
      - internal_network
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL',"curl -s --noproxy localhost localhost:3000/health | grep -q 'OK' || exit 1"]
    ports:
      - '127.0.0.1:3001:3000'
    depends_on:
      - db
      - redis
      # - es
    volumes:
      - ./public/system:/mastodon/public/system

  streaming:
    # You can uncomment the following lines if you want to not use the prebuilt image, for example if you have local code changes
    # build:
    #   dockerfile: ./streaming/Dockerfile
    #   context: .
    image: ghcr.io/mastodon/mastodon-streaming:v4.3.1
    restart: always
    env_file: .env.production
    command: node ./streaming/index.js
    networks:
      - external_network
      - internal_network
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', "curl -s --noproxy localhost localhost:4000/api/v1/streaming/health | grep -q 'OK' || exit 1"]
    ports:
      - '127.0.0.1:4000:4000'
    depends_on:
      - db
      - redis

  sidekiq:
    # build: .
    image: ghcr.io/mastodon/mastodon:v4.3.1
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]

  ## Uncomment to enable federation with tor instances along with adding the following ENV variables
  ## http_hidden_proxy=http://privoxy:8118
  ## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
  # tor:
  #   image: sirboops/tor
  #   networks:
  #      - external_network
  #      - internal_network
  #
  # privoxy:
  #   image: sirboops/privoxy
  #   volumes:
  #     - ./priv-config:/opt/config
  #   networks:
  #     - external_network
  #     - internal_network

networks:
  external_network:
  internal_network:
    internal: true
```

Run `docker-compose run --rm web bundle exec rake mastodon:setup`

### Expected behaviour

I am able to send emails with the correct SMTP credentials

### Actual behaviour

I get a Postfix error when I attempt to authenticate with the correct credentials

### Mastodon instance

mastodon.revsuine.xyz

### Mastodon version

v4.3.1

### Environment

Please at least include those informations:
- Operating system: Alpine Linux 3.20.3
- Ruby version: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) +YJIT [x86_64-linux]
- Node.js version: v20.18.0
- Mastodon using `docker-compose`
