### ISSUE TITLE
Elasticsearch::Transport::Transport::Errors::BadGateway ([502] )

### ISSUE THREAD

**Issue by cethink** [mastodon/mastodon#34711]
### Steps to reproduce the problem

Fresh installation.
500 pops up in the lower left corner when searching.
Show "Could not connect to Elasticsearch. Please check that it is running, or disable full-text search" in /admin/dashboard.

docker-compose.yml
```
  es:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true"
      - "xpack.license.self_generated.type=basic"
      - "xpack.security.enabled=false"
      - "xpack.watcher.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.ml.enabled=false"
      - "bootstrap.memory_lock=true"
      - "cluster.name=es-mastodon"
      - "discovery.type=single-node"
      - "thread_pool.write.queue_size=1000"
    networks:
       - external_network
       - internal_network
    healthcheck:
       test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
    volumes:
       - ./elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - '9233:9200'

  web:
    # You can uncomment the following line if you want to not use the prebuilt image, for example if you have local code changes
    # build: .
    image: ghcr.io/mastodon/mastodon:v4.3.8
    restart: always
    env_file: .env.production
    command: bundle exec puma -C config/puma.rb
    networks:
      - external_network
      - internal_network
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL',"curl -s --noproxy localhost localhost:3000/health | grep -q 'OK' || exit 1"]
    ports:
      - '8033:3000'
    depends_on:
      - db
      - redis
      - es
    volumes:
      - ./public/system:/mastodon/public/system
```

.env.production
```
# Elasticsearch (optional)
# ------------------------
ES_ENABLED=true
ES_HOST=es
ES_PORT=9233
# Authentication for ES (optional)
ES_USER=elastic
ES_PASS=elastic
```

### Expected behaviour

can search

### Actual behaviour

can't search

### Technical details

Mastodon | 4.3.8
-- | --
Ruby | 3.3.5p100
PostgreSQL | 14.18
Redis | 7.4.3
libvips | 8.15.3
FFmpeg | 7.0.2

docker compose logs web
```
I, [2025-05-16T20:00:14.703994 #17]  INFO -- : [bbfb2da3-2e55-4a40-811d-141d0a5cbab6] method=GET path=/api/v2/search format=html controller=Api::V2::SearchController action=index status=500 allocations=2691 duration=384.03 view=0.00 db=1.77
web-1  | E, [2025-05-16T20:00:14.704830 #17] ERROR -- : [bbfb2da3-2e55-4a40-811d-141d0a5cbab6]   
web-1  | [bbfb2da3-2e55-4a40-811d-141d0a5cbab6] Elasticsearch::Transport::Transport::Errors::BadGateway ([502] ):
web-1  | [bbfb2da3-2e55-4a40-811d-141d0a5cbab6]   
web-1  | [bbfb2da3-2e55-4a40-811d-141d0a5cbab6] app/services/account_search_service.rb:222:in `from_elasticsearch'
web-1  | [bbfb2da3-2e55-4a40-811d-141d0a5cbab6] app/services/account_search_service.rb:191:in `search_results'
web-1  | [bbfb2da3-2e55-4a40-811d-141d0a5cbab6] app/services/account_search_service.rb:166:in `search_service_results'
web-1  | [bbfb2da3-2e55-4a40-811d-141d0a5cbab6] app/services/account_search_service.rb:155:in `block in call'
web-1  | [bbfb2da3-2e55-4a40-811d-141d0a5cbab6] app/services/account_search_service.rb:142:in `call'
web-1  | [bbfb2da3-2e55-4a40-811d-141d0a5cbab6] app/services/search_service.rb:31:in `perform_accounts_search!'
web-1  | [bbfb2da3-2e55-4a40-811d-141d0a5cbab6] app/services/search_service.rb:21:in `block in call'
web-1  | [bbfb2da3-2e55-4a40-811d-141d0a5cbab6] app/services/search_service.rb:15:in `call'
web-1  | [bbfb2da3-2e55-4a40-811d-141d0a5cbab6] app/controllers/api/v2/search_controller.rb:49:in `search_results'
web-1  | [bbfb2da3-2e55-4a40-811d-141d0a5cbab6] app/controllers/api/v2/search_controller.rb:18:in `index'
web-1  | [bbfb2da3-2e55-4a40-811d-141d0a5cbab6] app/controllers/concerns/localized.rb:11:in `set_locale'
web-1  | [bbfb2da3-2e55-4a40-811d-141d0a5cbab6] lib/mastodon/rack_middleware.rb:9:in `call'
web-1  | [bbfb2da3-2e55-4a40-811d-141d0a5cbab6] lib/public_file_server_middleware.rb:18:in `call'
```
