### ISSUE TITLE
imports in custom.scss won't be loaded in order

### ISSUE THREAD

**Issue by unarist** [mastodon/mastodon#3930]
custom.scss

```scss
@import 'application';
@import 'custom_include.css';
```

custom_include.css

```css
body {
    content: "This style should be loaded after application.scss"
}
```

Output (application.css):

```css
/* (snip) */

.sr-only-focusable:active, .sr-only-focusable:focus {
  position: static;
  width: auto;
  height: auto;
  margin: 0;
  overflow: visible;
  clip: auto;
}@charset "UTF-8";

body {
    content: "This style should be loaded after application.scss"
}

@font-face {
  font-family: 'mastodon-font-sans-serif';
  src: local("Roboto"), url(http://localhost:8080/packs/roboto-italic-webfont.woff2) format("woff2"), url(http://localhost:8080/packs/roboto-italic-webfont.woff) format("woff"), url(http://localhost:8080/packs/roboto-italic-webfont.ttf) format("truetype"), url(http://localhost:8080/packs/roboto-italic-webfont.svg#roboto-italic-webfont) format("svg");
  font-weight: normal;
  font-style: italic;
}

/* (snip) */
```

It seems to be loaded between fontawesome and application.scss.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).
