### ISSUE TITLE
Accessibility issue with privacy/content warning controls in the tootbox

### ISSUE THREAD

**Issue by moggers87** [mastodon/mastodon#6028]
(This was originally a comment on #5824)

The privacy/content-warning buttons are not properly accessible - they can be selected via keyboard, but they don't offer much visual feedback. Compare with the emoji and "Toot" buttons:

1. Emoji selected:
![Emoji selected](https://user-images.githubusercontent.com/1490673/33609741-2ec8a7f0-d9c1-11e7-9609-a101a3699981.png)

2. "Toot" selected:
![Toot selected](https://user-images.githubusercontent.com/1490673/33609742-2eead2e4-d9c1-11e7-988f-34ef454c5aba.png)

3. Privacy button selected (note the limited contrast between the buttons)
![privacy button selected](https://user-images.githubusercontent.com/1490673/33609744-2f0dd6b8-d9c1-11e7-80c0-7047ce44954f.png)

For those of you unfamiliar with keyboard control in browsers: click the textbox and hit tab a bunch of times, you'll first see the emoji button selected (if you press space or enter, you'll get the emoji picker pop up). If you hit tab a few more times you'll see the "Toot" button is selected - hitting space or enter here will post your toot.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by moggers87** [comment]
These W3C document on [colour contrast](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html) and on [indicating keyboard focus](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html) might be worth a read too

**Comment by Xkeeper0** [comment]
If you have some form of User CSS available, you can make them more usable by using the following CSS. This will also add a background showing the available clicking area to the buttons as well.

Focusing a button and then its active state:
![image](https://user-images.githubusercontent.com/1077535/34888020-67af9bbc-f77d-11e7-9adf-8f16eccbc890.png) ![image](https://user-images.githubusercontent.com/1077535/34888025-6b3729a8-f77d-11e7-9011-26b6ea7c41a6.png)

Toggled "CW" button:
![image](https://user-images.githubusercontent.com/1077535/34888037-77bba3de-f77d-11e7-82e5-6adcf3f47492.png)


For posterity, the default look without this CSS:
![image](https://user-images.githubusercontent.com/1077535/34888099-b9390c2a-f77d-11e7-8ca4-4d307ef0b904.png)


```css
.compose-form__buttons button {
    /* make the new toot buttons stand out too */
	background: rgba(0, 0, 0, .2);
	border-radius: .3em;
	color: #fff;
	margin-right: .5em;
}

.compose-form__buttons button.active {
	/* make the cw button more obvious when toggled */
	background: rgba(0, 0, 0, .6);
	color: #ff4;
	box-shadow: inset 0px 2px 3px 1px rgba(0, 0, 0, .6);
}
	
.compose-form__buttons button:hover, .compose-form__buttons button:focus {
	/* make all the buttons stand out when you hover over them */
	background: rgba(0, 0, 0, .4);
	color: #fff;
}
```
