### ISSUE TITLE
Moved account box not shown on profile page at small widths

### ISSUE THREAD

**Issue by dracos** [mastodon/mastodon#8563]
At small widths on a profile page, `column-1` is hidden which includes the `moved-account-widget`. The `public-account-bio` part of the column is replicated in `public-account-header__extra`, so it seems like it would make sense to duplicate the moved widget there also.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Krinkle** [comment]
This is still an issue as of v3.5.3. The impact is that it's near impossible to find where the person has moved to, or even to know that the person has moved at all (though an experience Mastodon user might recognise this from the dimmed header photo).

Similar to what @dracos I made the same observation, that the bio text is already "fixed" by outputting it twice and hiding by default the one that is part of the header, but showing it when hiding `column-1`. I would suggest doing the same for the `moved-account-widget` element.

When I move it manually in devtools, the main issue I find is that the `opacity: 0.5` rule for the `.public-layout .public-account-header.inactive` container is affecting this widget as well. 

The following could work as a way to make it render normally:

```css
.public-layout .public-account-header.inactive .public-account-header__image,
.public-layout .public-account-header.inactive .public-account-header__bar > :not(.public-account-header__extra),
.public-layout .public-account-header.inactive .public-account-header__extra > :not(.moved-account-widget) {
 opacity: .5;
}
```

The next issue is the limited width and rendering style not fitting well. There is already an existing CSS rule that makes the bio accomodate to this context (reset border-radius, negative margin to undo padding). Put together, it looks as follows:

| Wide (unchanged) | Narrow (today) | Narrow (proposed)
|--|--|--
| ![Screenshot](https://user-images.githubusercontent.com/156867/195928174-0bc2087f-6fa7-4245-9567-fdccaaa5281c.png) | ![Screenshot](https://user-images.githubusercontent.com/156867/195928184-a325e7af-2389-4c80-8cbf-9cbeeed59293.png) | ![Screenshot](https://user-images.githubusercontent.com/156867/195928181-66195849-c8f5-4b5e-bcd6-208ea7c0b2a6.png)
